### ISSUE TITLE
The generate_pod! macro failed

### ISSUE THREAD

**Issue by testforvln** [google/autocxx#1019]
## Expected Behavior
compiles fine

## Actual Behavior
  Error: 
    × the include_cpp! macro couldn't be expanded into Rust bindings to C++:
    │ autocxx could not generate the requested bindings

## Steps to Reproduce the Problem

1. unzip the file
1. cargo build

## Specifications

- Version: 0.20.0
- Platform: ubuntu 20.04

[ctp-autocxx-junk.zip](https://github.com/google/autocxx/files/8459298/ctp-autocxx-junk.zip)

**Comment by adetaylor** [comment]
Thanks for the report. I can reproduce it, and I've never seen such a useless error message omitted from autocxx, so something definitely needs fixing here.

I've tried to build a minimized test case but my minimization pipeline reckons that something in one of the headers is not valid UTF-8, so that might be a clue. I'll look more during the next few days.

**Comment by testforvln** [comment]
> Thanks for the report. I can reproduce it, and I've never seen such a useless error message omitted from autocxx, so something definitely needs fixing here.
> 
> I've tried to build a minimized test case but my minimization pipeline reckons that something in one of the headers is not valid UTF-8, so that might be a clue. I'll look more during the next few days.

The header file's encoding is gbk. Hope it helps.

**Comment by adetaylor** [comment]
OK, the fixed error message says:

```
    × the include_cpp! macro couldn't be expanded into Rust bindings to C++:
    │ An item was requested using 'generate_pod' which was not safe to hold by
    │ value in Rust. Type CThostFtdcReqUserLoginField could not be POD because
    │ its dependent type TThostFtdcDateType isn't safe to be POD. Because: Type
    │ TThostFtdcDateType is a typedef to a complex type

```

Thanks for highlighting that the error message was faulty and was hiding this important information. I'm fixing that in #1021.

**Comment by testforvln** [comment]
> OK, the fixed error message says:
> 
> ```
>     × the include_cpp! macro couldn't be expanded into Rust bindings to C++:
>     │ An item was requested using 'generate_pod' which was not safe to hold by
>     │ value in Rust. Type CThostFtdcReqUserLoginField could not be POD because
>     │ its dependent type TThostFtdcDateType isn't safe to be POD. Because: Type
>     │ TThostFtdcDateType is a typedef to a complex type
> ```
> 
> Thanks for highlighting that the error message was faulty and was hiding this important information. I'm fixing that in #1021.

Thanks for your quick reply. But I still have problems with constructing a CThostFtdcReqUserLoginField object with CThostFtdcReqUserLoginField::new(), which come up with error showing that the new() function or associated item not found in root::CThostFtdcReqUserLoginField,
I just change src/junk/mod.rs into
```
use autocxx::prelude::*;
use autocxx::subclass::*;

include_cpp! {
    #include "ThostFtdcUserApiStruct.h"

    safety!(unsafe_ffi)

    generate!("CThostFtdcReqUserLoginField")
}


use ffi::*;
use autocxx::subclass::CppSubclassDefault;
use std::pin::Pin;
use cxx::std::convert::TryFrom;



pub fn test_md() {
     let mut req_user_login_field = ffi::CThostFtdcReqUserLoginField::new();

}
```
How can I modify the code so that I can contruct this CThostFtdcReqUserLoginField object?

**Comment by adetaylor** [comment]
I've raised this problem as #1034. However even if that's fixed, you'll struggle with this codebase because it's heavily reliant on fields rather than methods, and until we do #53 there is no way to access those fields. PRs welcome!

**Comment by guotie** [comment]
```
include_cpp! {
    #include "wrapper.hpp"
    safety!(unsafe)
    generate_pod!("CThostFtdcRspUserLoginField")
}
```

I got this err: 
```
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(AutocxxCodegenError(Conversion(Cpp(UnsafePodType("Type CThostFtdcUserLogoutField could not be POD because its dependent type TThostFtdcBrokerIDType isn't safe to be POD. Because: Type TThostFtdcBrokerIDType is a typedef to a complex type")))))', build.rs:39:18
```

C++ definitions:
```
typedef char TThostFtdcDateType[9];

typedef char TThostFtdcBrokerIDType[11];

struct CThostFtdcReqUserLoginField
{
	TThostFtdcDateType	TradingDay;
	TThostFtdcBrokerIDType	BrokerID;
	TThostFtdcUserIDType	UserID;
....
}

```

**Comment by adetaylor** [comment]
Yep, unfortunately arrays aren't supported yet by cxx or autocxx.
