### ISSUE TITLE
Support Variadic Arguments

### ISSUE THREAD

**Issue by yuxuan-xie** [google/autocxx#1075]
When a cpp function signature includes some kind of variadic argument
``` c++
class SomeClass{
  void foo( int a, ... )
}
```
autocxx will crush during building due to the incompatibility of the function pointer. ( I guess this is because that autocxx engine does not parse the variadic argument, which further makes the c++ generator unable to generate correct signature for the wrapper function.)
```
error: cannot initialize a variable of type 'void (SomeClass::*)(::c_int)' with an rvalue of type 'void (SomeClass::*)(int, ...)'
warning:   void (::SomeClass::*foo$)(::c_int) = &::SomeClass::foo;
```

Additionally, rust has enabled the c-variadic feature for `extern "C"` block since https://doc.rust-lang.org/beta/unstable-book/language-features/c-variadic.html, and bindgen fully supports it. I'm not sure whether cxx supports that. If it is the case, then fixing autocxx might be fairly easy.

**Comment by adetaylor** [comment]
I regard it as a clear bug that this causes generation to fail. We should, for now, ignore these variadic arguments and I'll work on that soon.

I'm going to close this issue once that's fixed.

Actually _supporting_ them is another matter. I'd be happy to accept a pull request, but it may require contributions to cxx too.
