### ISSUE TITLE
It seems that autocxx cannot generate_pod a POD struct with union type in it

### ISSUE THREAD

**Issue by Wade-Lee** [google/autocxx#1113]
## Expected Behavior
compiles fine

## Actual Behavior
Error: 
  × the include_cpp! macro couldn't be expanded into Rust bindings to C+
  │ +: An item was requested using 'generate_pod' which was not safe to hold
  │ by value in Rust. Type XTPMarketDataStruct could not be POD because its
  │ dependent type XTPMarketDataStruct__bindgen_ty_1 isn't known

## Steps to Reproduce the Problem

1.unzip the attached file
2.cargo build

## Specifications

- Version: 0.22.0
- Platform: CentOS 8.3.2011

## Failure Reason: 
generate_pod!("XTPMarketDataStruct")  Line 9 in xtp.rs
Because XTPMarketDataStruct contains one C++ union type.
When I comment the union type as below, it compiles:
    // union {
    //     XTPMarketDataStockExData  stk;
    //     XTPMarketDataOptionExData opt;
    //     XTPMarketDataBondExData  bond;
    // } ;

[gateway_xtp.zip](https://github.com/google/autocxx/files/8777722/gateway_xtp.zip)

**Comment by adetaylor** [comment]
Thanks for the report. This is a known limitation, and the diagnostics look reasonable, so I'm going to mark this issue as closed. I'd happily accept a pull request to remove this limitation if you like.
