### ISSUE TITLE
crubit?

### ISSUE THREAD

**Issue by bc-lee** [google/autocxx#1124]
I saw another project called crubit and it looks like it's still in development. https://crbug.com/1296155#c25 https://github.com/google/crubit

Is there any possibility that crubit will replace autocxx?

**Comment by adetaylor** [comment]
Yep, it's possible! crubit evolved from the early designs of autocxx. It has slightly different goals. cxx compatibility isn't a goal; it prioritizes support for a wider set of C++ features. We'll see how things shake out!
