### ISSUE TITLE
`autocxx_gen` segfaults on this code

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#1125]
```cpp
namespace {
namespace {
template <class a> class b {
  typedef a c;
  struct {
    c : sizeof(c);
  };
};
} // namespace
} // namespace
```

**Comment by adetaylor** [comment]
Hm, this appears only to crash when used with a specific version of libclang.

**Comment by adetaylor** [comment]
Er, the ASAN build on CI is crashing in libclang 12!

Next steps here: @chbaker0 to educate me on how we can most easily test this against an ASAN build of clang itself.

**Comment by chbaker0** [comment]
Does Clang 12 crash when attempting to compile that code?
