### ISSUE TITLE
libtorrent-rasterbar: Encountered type not yet supported by autocxx: [u32 ; 5usize]

### ISSUE THREAD

**Issue by vorot93** [google/autocxx#1151]
I'm trying to generate [bindings for libtorrent-rasterbar](https://github.com/vorot93/libtorrent-rasterbar-rs). Upon enabling `libtorrent::info_hash_t` ([reference](https://libtorrent.org/reference-Core.html#info_hash_t) | [source](https://libtorrent.org/include/libtorrent/info_hash.hpp)) I get this error:

```
Encountered type not yet supported by autocxx: [u32 ; 5usize]
```

Disabling it makes compile again.

I have not managed to pinpoint where the error comes from exactly.

**Comment by adetaylor** [comment]
Yep. We don't support arrays - #266. Pull requests welcome.
