### ISSUE TITLE
Cross-compiling libraries

### ISSUE THREAD

**Issue by bobbbay** [google/autocxx#1159]
## Expected Behavior

To be able to compile to another architecture just fine.

## Actual Behavior

Autocxx generates an x86-64 library, and makes my linker unhappy.

## Steps to Reproduce the Problem

1. Create a build.rs with the following:

```rust
    let mut b = autocxx_build::Builder::new("src/lib.rs", &[&libraries_path])
        .extra_clang_args(&[
            "-std=c++17",
            "-stdlib=libc++",
            "--target=arm-unknown-linux-gnueabi",
        ])
        .build()?;

    b.flag_if_supported("-std=c++17")
        .flag_if_supported("-stdlib=libc++")
        .flag_if_supported("--target=arm-unknown-linux-gnueabi")
        .compile("x");
```

2. Compile with `--target arm-unknown-linux-gnueabi`
3. Verify that the library is built for x86-64 with `objdump -f $out/libx.a`:

```
In archive ...:

gen0.o:     file format elf64-x86-64
architecture: i386:x86-64, flags 0x00000011:
HAS_RELOC, HAS_SYMS
start address 0x0000000000000000
```

## Specifications

- Version: `0.22.4`
- Platform: `x86_64-linux`

**Comment by bobbbay** [comment]
In other words, how do I ask autocxx to cross-compile?

**Comment by adetaylor** [comment]
autocxx (or cxx) just generate the C++, and then give you a [`cc::Build`](https://docs.rs/cc/latest/cc/struct.Build.html) object. So, really you should be looking into how to achieve cross-compilation using the `cc` crate. It [says that cross compilation is determined according to the flags set by cargo](https://docs.rs/cc/latest/cc/) but I don't have more details.

**Comment by bobbbay** [comment]
It seems I had to set the `CROSS_COMPILE` environment variable to 1 in order for the `cc` crate to cross compile :). I also specified the compiler with `.compiler()`. Thanks!
