### ISSUE TITLE
extern_rust_type not being generated

### ISSUE THREAD

**Issue by johalun** [google/autocxx#1161]
## Expected Behavior
Rust structures annotated with #[extern_rust_type] should be generated

## Actual Behavior
extern_rust_type annotated structs are not generated, however extern_rust_function is.

## Steps to Reproduce the Problem

1.
Add this to examples/steam-mini/src/main.rs
```
#[extern_rust_type]
struct Foo;

#[extern_rust_function]
fn foo() {}
```

2.
run `cargo build`

3.
Find that bindings for `fn foo` have been generated but not `struct Foo`.

## Specifications

- Version: v0.22.4
- Platform: macOS Monterey and Ubuntu 20.04

**Comment by adetaylor** [comment]
Thanks for this report. I'm juggling a few things now so I haven't had a chance to refresh my memory in this area. I'll get there eventually but meanwhile it's possible that [this option might help](https://docs.rs/autocxx-engine/0.22.4/autocxx_engine/struct.Builder.html#method.auto_allowlist) in your `build.rs`.

**Comment by adetaylor** [comment]
Fixed by the above pull request, although note that it also changes the documentation to explain that you probably need to forward-declare such types.
