### ISSUE TITLE
#include "cxx.h" causes the build script to rerun indefinitely

### ISSUE THREAD

**Issue by jerry73204** [google/autocxx#1196]
Simply putting `#incude "cxx.h"` in the C++ header file always causes `build.rs` to rerun. The `cxx.h` header is automatically provided. I suspect that the `cxx.h` is created on the fly in compile time so that the fresh timestamp triggers the rerun.

Here is the minimal reproducing example.

- `include/example.hpp`

```c++
#pragma once
#include <cxx.h>
```

- `src/lib.rs`
```rust
use autocxx::prelude::*;

include_cpp! {
    #include <example.hpp>
    safety!(unsafe_ffi)
}
```

- `build.rs`
```rust
autocxx_build::Builder::new("src/lib.rs", &["include"])
    .build()
    .unwrap()
    .compile("exmaple");
```

**Comment by adetaylor** [comment]
Thanks, I can see why this is happening and I am working on a fix.
