### ISSUE TITLE
Can not mix `include_cpp!` and `#[cxx::bridge]`

### ISSUE THREAD

**Issue by oblique** [google/autocxx#1197]
I was following the book and I can not get `include_cpp!` and `#[cxx::bridge]` to work together.
Am I doing something wrong? Or this is a bug?

## Expected Behavior

`cxxgen.h` contain both `include_cpp!` generation and `#[cxx::bridge]` generation.

## Actual Behavior

`cxxgen.h` contains only `#[cxx::bridge]` generation.

## Steps to Reproduce the Problem

1. These are my sources

Cargo.toml:
```toml
[package]
name = "autocxx-example"
version = "0.1.0"
edition = "2021"

[dependencies]
autocxx = "0.23.1"
cxx = "1.0.83"

[build-dependencies]
anyhow = "1.0.66"
autocxx-build = "0.23.1"
```

build.rs:
```rust
use anyhow::Result;

fn main() -> Result<()> {
    let path = std::path::PathBuf::from("src");
    let mut b = autocxx_build::Builder::new("src/main.rs", &[&path]).build()?;
    b.flag_if_supported("-std=c++14").file("src/deep.cc").compile("autocxx-demo");

    println!("cargo:rerun-if-changed=src/main.rs");
    println!("cargo:rerun-if-changed=src/deep.cc");
    println!("cargo:rerun-if-changed=src/deep.h");
    println!("cargo:rerun-if-changed=src/input.h");

    println!("cargo:rustc-link-lib=stdc++");

    Ok(())
}
```

src/main.rs:
```rust
use autocxx::extern_rust::extern_rust_function;
use autocxx::prelude::*;

include_cpp! {
    #include "deep.h"
    safety!(unsafe)
    generate!("DeepThought")
    extern_cpp_opaque_type!("Input", ffi2::Input)
}

#[cxx::bridge]
mod ffi2 {
    unsafe extern "C++" {
        include!("input.h");
        type Input;
    }
}

fn main() {
    println!("The answer to Life, The Universe and Everything is {}", ffi::DeepThought());
}

#[extern_rust_function]
pub fn call_me_from_cpp() {
    println!("Rust called from cpp");
}
```

src/deep.h:
```c++
#pragma once

#include <string>

std::string DeepThought();
```

src/deep.cc:
```c++
#include "deep.h"
#include "cxxgen.h"

std::string DeepThought() {
    call_me_from_cpp();
    return std::string("bla bla");
}
```

src/input.h:
```c++
#pragma once

struct Input {
    int val;
};
```

2. Run `cargo run`, the following error will be produced:

```
  cargo:warning=src/deep.cc: In function ‘std::string DeepThought()’:
  cargo:warning=src/deep.cc:5:5: error: ‘call_me_from_cpp’ was not declared in this scope
  cargo:warning=    5 |     call_me_from_cpp();
  cargo:warning=      |     ^~~~~~~~~~~~~~~~
  exit status: 1
  ```

3. `target/debug/build/autocxx-example-*/out/autocxx-build-dir/include/cxxgen.h` contains only code generation of `#[cxx::bridge]`

```c++
#pragma once
#include "input.h"

using Input = ::Input;
```

## Specifications

- Version:  autocxx 0.23.1, cxx 1.0.83
- Platform: Linux

**Comment by adetaylor** [comment]
Sorry for the slow reply here. Normally I ask folks filing bugs to [raise pull requests with a failing test case](https://google.github.io/autocxx/contributing.html#reporting-bugs), but due to the complexity of this case that's quite a tall order, it wouldn't fit too well into the structure of the test cases. I'll aim to find time to actually reproduce it.

(But in summary - yes, what you're trying to do _should_ work unless I've forgotten some obvious limitation)
