### ISSUE TITLE
use of moved value

### ISSUE THREAD

**Issue by 513153980** [google/autocxx#1198]
## Actual Behavior
use of moved value: `api`
value used here after move

## Steps to Reproduce the Problem
c++ ThostFtdcMdApi.h:
class MD_API_EXPORT CThostFtdcMdApi
{
public:
	static CThostFtdcMdApi *CreateFtdcMdApi(const char *pszFlowPath = "", const bool bIsUsingUdp=false, const bool bIsMulticast=false);

	virtual void RegisterFront(char *pszFrontAddress) = 0;

	virtual void RegisterNameServer(char *pszNsAddress) = 0;
protected:
	~CThostFtdcMdApi(){};
};

rust:
use autocxx::{prelude::*, subclass::*};
use std::{ffi::*, pin::Pin};
use ffi::*;

include_cpp! {
    #include "ThostFtdcMdApi.h"
    safety!(unsafe_ffi)
    generate!("CThostFtdcMdApi")
}

fn main() {
    unsafe {
        let api = Pin::new_unchecked(CThostFtdcMdApi::CreateFtdcMdApi(CString::new("").unwrap().into_raw(), false, false).as_mut().unwrap());
        api.RegisterFront(CString::new("").unwrap().into_raw());
        api.RegisterNameServer(CString::new("").unwrap().into_raw());
    }
}

## Specifications

- Version:0.23.1
- Platform:windows

**Comment by adetaylor** [comment]
Thanks, and sorry for the slow reply here. Would you be kind enough to raise a pull request with a [failing test case, using these instructions](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs)?

**Comment by adetaylor** [comment]
There's a chance that this has been fixed by some recent changes. In any case I'm not going to attempt to reproduce this from the limited information above - experience suggests it's just very unlikely to reproduce.
