### ISSUE TITLE
Compile to `cdylib` error

### ISSUE THREAD

**Issue by VirxEC** [google/autocxx#1200]
## Expected Behavior

The project should compile without error even when I have this in my `Cargo.toml`:
```toml
[lib]
crate-type = ["cdylib"]
```

## Actual Behavior

I get this error:

```
error: failed to run custom build command for `package-rs v0.1.0 (/home/asdf/Documents/package-rs)`

Caused by:
  process didn't exit successfully: `/home/asdf/Documents/package-rs/target/release/build/package-rs-6656c500e65db2fb/build-script-build` (exit status: 1)
  --- stderr
  Error: 
    × unable to open the source file: No such file or directory (os error 2)
```

I have confirmed that the file exists on my machine.

## Steps to Reproduce the Problem

1. Create working links with `main.rs` and `main` function
1. Try to convert to `lib.rs`, remove `main` function (opt for it as a test instead) and set `crate-type = ["cdylib"]`
1. `cargo b`

## Specifications

- Version: `autocxx 0.23.1`, `autocxx-build 0.23.1`, `cxx 1.0.83`
- Platform: Ubuntu 22.10

**Comment by adetaylor** [comment]
I strongly suspect this is because your source code is now called `lib.rs` instead of `main.rs` but you haven't updated the `build.rs` to say so.

Please check your `build.rs` and let me know whether that's the outcome.

The diagnostic here is terrible though, so I'll keep this open to improve it.

**Comment by VirxEC** [comment]
Rip thanks, that was it and yeah the diagnostic could definitely use a little bit of work, even if it just gives the name of the file it can't find that would be a lot better.
