### ISSUE TITLE
no_std support (with and without alloc)

### ISSUE THREAD

**Issue by kitlith** [google/autocxx#1204]
autocxx currently generates code that refers to `std::pin::Pin` and a few other types that could instead refer to core or alloc (for string). To support no_std, these types can simply refer to core and alloc instead. Ideally there would also be a way to remove the codegen for the String type as well, to support usecases without alloc.

That said, the usecases for this might be limited by cxx's dependence on lib(std)c++. (I wonder if a minimal polyfill could be built for it? food for thought.)

I hacked together a [branch](https://github.com/kitlith/autocxx/tree/no_std) to try it out, and was at least able to get it to successfully 'check' for a no_std target, though i never attempted to compile/run due to the libc++ issue. The main blocker to this being submitted as a PR is the straight up removal of some code generating references to `std::string::String` -- that should be replaced with `alloc::string::String`, and eventually placed behind a conditional whether to include it or not. (or maybe only include it if any of the autocxx code is actually dealing with strings)

The code I was testing with is here: https://github.com/kitlith/vqf-cxx/tree/no_std

**Comment by kitlith** [comment]
Thanks for reminding me about this! I'll see if I can get the less hacky parts in as a PR. (I think the hacky part may actually be unnecessary given exclude_utilities, but another way or clearer documentation may be desired.)

**Comment by adetaylor** [comment]
Yep. Happy to accept an incremental PR to just do the easy bits.

**Comment by HikingDev** [comment]
Does autocxx support no_std by now?
cxx does support no_std but when using autocxx, cxx is a dependency and not build with default-features = false and features = ["alloc"]
