### ISSUE TITLE
Build fail after adding concrete type

### ISSUE THREAD

**Issue by VirxEC** [google/autocxx#1205]
## Expected Behavior

The ideal case is to generate the type, but more realistically it shouldn't crash.

## Actual Behavior

Crashes on the build step

## Steps to Reproduce the Problem

1. Have a type like this:
```cpp
template <int n>
class vec {
  float data[n];

 public:
  vec() {}
};
```
2. Try to make a concrete type:
```rust
autocxx::include_cpp! {
    #include "vec.h"
    safety!(unsafe)
    concrete!("vec<3>", vec3)
}
```
3. It crashes on the build step:
```
error: failed to run custom build command for `thing v0.1.1 (/home/virx/Documents/thing-rs)`

Caused by:
  process didn't exit successfully: `/home/virx/Documents/thing-rs/target/debug/build/thing-f00e95680aaf6021/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=file.h
  [a lot more cargo:rerun-if-changed]

  --- stderr
  thread 'main' panicked at 'internal error: entered unreachable code', /home/virx/.cargo/registry/src/github.com-1ecc6299db9ec823/autocxx-parser-0.23.1/src/config.rs:327:42
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

There is also a `typedef vec<3> vec3;` that I tried to generate with `generate!("vec3", vec3)` but it produced `type vec3 = [u32; 3]`. I think it actually got it, but there's another bug that caused it to either error generating a struct with `_data: [u8; 12]` or `type vec3 = [f32; 3];`.

## Specifications

- Version: 0.23.1
- Platform: Ubuntu 22.10 x86_64

**Comment by adetaylor** [comment]
Thanks, would you be kind enough to raise a PR with a [minimal test](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs)?

**Comment by adetaylor** [comment]
OK no problem. I reckon you've given me enough to reproduce this - I'll give it a try. Thanks for at least having a go at making a reproducible test case.

**Comment by VirxEC** [comment]
This is the file in the project that I'm trying to link to: <https://github.com/samuelpmish/RLUtilities/blob/develop/inc/linear_algebra/vec.h> if that helps.

**Comment by adetaylor** [comment]
Unfortunately I can't reproduce this. I spent some time scratching my head trying to work out how you could possibly have hit the `unreachable!` at `autocxx-parser-0.23.1/src/config.rs:327` but I can't spot it. Sorry, I think I'll need a repro case. Good luck meanwhile!
