### ISSUE TITLE
Generated #[repr(c_char16_t)] does not compile

### ISSUE THREAD

**Issue by Moocow9m** [google/autocxx#1214]
## Expected Behavior
Generated code compiles

## Actual Behavior
`error[E0552]: unrecognized representation hint` is generated.
Note: Error is generated on `enum class DispatchKey : uint16_t`

## Steps to Reproduce the Problem

1. Make autocxx generate bindings for pytorch c++ api (https://hastebin.com/ofopiboxac.cpp)
2. Compile

## Specifications

- Version: 0.23.1
- Platform: Windows
- Rust: Nightly&Stable
- Clang: 15.0.7

**Comment by adetaylor** [comment]
Thanks for the report. This sounds like a real bug. Please could you follow [the instructions here](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs) to add a minimal test case, or at the very least, provide a reproduction JSON?

**Comment by Moocow9m** [comment]
> Thanks for the report. This sounds like a real bug. Please could you follow [the instructions here](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs) to add a minimal test case, or at the very least, provide a reproduction JSON?

I failed to get the repro tool working so I made the JSON instead. I'll look to see if I can make a minimal example later without the tool.
[repro.json](https://github.com/google/autocxx/files/10537681/repro.txt)

**Comment by adetaylor** [comment]
Thanks for trying! I succeeded in adding a test in #1223, no need for you to do anything else.

**Comment by adetaylor** [comment]
bindgen is giving us:

```rust
    #[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
    pub mod root {
        #[allow(unused_imports)]
        use self::super::root;
        pub mod std {
            #[allow(unused_imports)]
            use self::super::super::root;
        }
        #[repr(c_char16_t)]
        #[derive(Clone, Hash, PartialEq, Eq)]
        pub enum C {
            A = 0,
            B = 1,
        }
    }
     }

```

**Comment by Moocow9m** [comment]
Perhaps my knowledge of how shorts are handled in rust is missing, but is there a reason why char16_t is handled that way?

**Comment by adetaylor** [comment]
It's just a bug, I'm just recording my notes-to-myself here as I'm only getting 30 seconds here and there between meetings to look into it so it might be days before I come back to it!

**Comment by Moocow9m** [comment]
Understood
