### ISSUE TITLE
Failed to build/run https://github.com/google/autocxx/tree/main/examples/s2

### ISSUE THREAD

**Issue by DCMinds** [google/autocxx#1215]
I have clone the autocxx archive and trying to run (on Windows) the example  https://github.com/google/autocxx/tree/main/examples/s2

But i am getting below error. we are getting liker error 

 Compiling autocxx-s2-example v0.1.0 (C:\WS\AXP\Rust\autocxx\examples\s2)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX64\\x64\\link.exe" "/NOLOGO" "C:\\Users\\chaudhd\\AppData\\Local\\Temp\\rustcLJjVKe\\symbols.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.12xsy12vy5szrp7z.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.1991cy43zfz7x9uu.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.1adnea9d3lmmvtym.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.1p2hdlemg9u8g9rx.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.2l6mmxjok20f7uhc.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.311yrloo9tbmxbpe.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.34z9xlrv0hdoc6ne.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3i0dcl84ilvrlqe9.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3j62fio2rzss0p9q.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3qlv11iu6sqe61lw.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3tm18wby2tmzn706.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3z2tj8oveggq0zmm.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.48bgjoduvk0527kp.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.492bnyuiiivg7mzy.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.4mqoifxsneb9byi6.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.4se71zfc87pg46kh.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.52q1raut20yqxv9m.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.5e88msm7xom5ukne.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.96uv2qr4hdwmfbf.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.diofxuidas07ufe.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.mv1bykfdop2c2to.rcgu.o" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.3jph85s37g5getk.rcgu.o" "/LIBPATH:C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\atlmfc\\lib\\x64" "/LIBPATH:C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\build\\autocxx-s2-example-5549f22e1b50c0ff\\out" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\atlmfc\\lib\\x64" "/LIBPATH:C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\build\\cxx-476284d107656fa9\\out" "/LIBPATH:C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\VC\\Tools\\MSVC\\14.29.30133\\atlmfc\\lib\\x64" "/LIBPATH:C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\build\\link-cplusplus-61f68e5305ac5bae\\out" "/LIBPATH:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "autocxx-s2-example.lib" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\libautocxx-18ab39f5477506c8.rlib" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\libmoveit-3e46a8d0164ce33e.rlib" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\libcxx-5fea5c66b536f68b.rlib" "C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\liblink_cplusplus-5c9c2d49caab560b.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-fdaa63d6970be740.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-a684236a9da37ec6.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_demangle-85c151aafb35bf5c.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_detect-7dbe75e48c9029c0.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libhashbrown-78044ac8790346aa.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libminiz_oxide-8743285c70baade8.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libadler-b260ead09cc3ca75.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-200564555b6c364f.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-60e4ae6d068e334f.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcfg_if-d74559c1731cb9bf.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-3d51e2979c44c27c.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-268ac0a196c81649.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librustc_std_workspace_core-e74895db82cfb265.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-d805a250e2b7e197.rlib" "C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-3f507ba7adac1c2a.rlib" "kernel32.lib" "advapi32.lib" "userenv.lib" "kernel32.lib" "ws2_32.lib" "bcrypt.lib" "msvcrt.lib" "legacy_stdio_definitions.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "/OUT:C:\\WS\\AXP\\Rust\\autocxx\\examples\\s2\\target\\debug\\deps\\autocxx_s2_example.exe" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\chaudhd\\.rustup\\toolchains\\stable-x86_64-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis"
  = note: autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: static class R2Rect __cdecl R2Rect::FromCenterSize(class Vector2<double> const &,class Vector2<double> const &)" (?FromCenterSize@R2Rect@@SA?AV1@AEBV?$Vector2@N@@0@Z) referenced in function "void __cdecl FromCenterSize_autocxx_wrapper(class Vector2<double> const &,class Vector2<double> const &,class R2Rect *)" (?FromCenterSize_autocxx_wrapper@@YAXAEBV?$Vector2@N@@0PEAVR2Rect@@@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: static class R2Rect __cdecl R2Rect::FromPointPair(class Vector2<double> const &,class 
Vector2<double> const &)" (?FromPointPair@R2Rect@@SA?AV1@AEBV?$Vector2@N@@0@Z) referenced in function "void __cdecl R2Rect_FromPointPair_autocxx_wrapper(class Vector2<double> const &,class Vector2<double> const &,class R2Rect *)" (?R2Rect_FromPointPair_autocxx_wrapper@@YAXAEBV?$Vector2@N@@0PEAVR2Rect@@@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl R2Rect::Contains(class R2Rect const &)const " (?Contains@R2Rect@@QEBA_NAEBV1@@Z) referenced in function "bool __cdecl R2Rect_Contains1_autocxx_wrapper(class R2Rect const &,class R2Rect const &)" (?R2Rect_Contains1_autocxx_wrapper@@YA_NAEBVR2Rect@@0@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl R2Rect::InteriorContains(class R2Rect const &)const " (?InteriorContains@R2Rect@@QEBA_NAEBV1@@Z) referenced in function "bool __cdecl R2Rect_InteriorContains1_autocxx_wrapper(class R2Rect const &,class R2Rect const &)" (?R2Rect_InteriorContains1_autocxx_wrapper@@YA_NAEBVR2Rect@@0@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl R2Rect::Intersects(class R2Rect const &)const " (?Intersects@R2Rect@@QEBA_NAEBV1@@Z) referenced in function "bool __cdecl R2Rect_Intersects_autocxx_wrapper(class R2Rect const &,class R2Rect const &)" (?R2Rect_Intersects_autocxx_wrapper@@YA_NAEBVR2Rect@@0@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl R2Rect::InteriorIntersects(class R2Rect const &)const " (?InteriorIntersects@R2Rect@@QEBA_NAEBV1@@Z) referenced in function "bool __cdecl R2Rect_InteriorIntersects_autocxx_wrapper(class R2Rect const &,class R2Rect const &)" (?R2Rect_InteriorIntersects_autocxx_wrapper@@YA_NAEBVR2Rect@@0@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl R2Rect::AddPoint(class Vector2<double> const &)" (?AddPoint@R2Rect@@QEAAXAEBV?$Vector2@N@@@Z) referenced in function "void __cdecl R2Rect_AddPoint_autocxx_wrapper(class R2Rect &,class Vector2<double> const &)" (?R2Rect_AddPoint_autocxx_wrapper@@YAXAEAVR2Rect@@AEBV?$Vector2@N@@@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: void __cdecl R2Rect::AddRect(class R2Rect const &)" (?AddRect@R2Rect@@QEAAXAEBV1@@Z) referenced in function cxxbridge1$R2Rect$AddRect
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: class Vector2<double> __cdecl R2Rect::Project(class Vector2<double> const &)const " (?Project@R2Rect@@QEBA?AV?$Vector2@N@@AEBV2@@Z) referenced in function "class std::unique_ptr<class Vector2<double>,struct std::default_delete<class Vector2<double> > > __cdecl R2Rect_Project_autocxx_wrapper(class R2Rect const &,class Vector2<double> const &)" (?R2Rect_Project_autocxx_wrapper@@YA?AV?$unique_ptr@V?$Vector2@N@@U?$default_delete@V?$Vector2@N@@@std@@@std@@AEBVR2Rect@@AEBV?$Vector2@N@@@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: class R2Rect __cdecl R2Rect::Expanded(class Vector2<double> const &)const " (?Expanded@R2Rect@@QEBA?AV1@AEBV?$Vector2@N@@@Z) referenced in function "public: class R2Rect __cdecl R2Rect::Expanded(double)const " (?Expanded@R2Rect@@QEBA?AV1@N@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: class R2Rect __cdecl R2Rect::Union(class R2Rect const &)const " (?Union@R2Rect@@QEBA?AV1@AEBV1@@Z) referenced in function "void __cdecl R2Rect_Union_autocxx_wrapper(class R2Rect const &,class R2Rect const &,class R2Rect *)" (?R2Rect_Union_autocxx_wrapper@@YAXAEBVR2Rect@@0PEAV1@@Z)  
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: class R2Rect __cdecl R2Rect::Intersection(class R2Rect const &)const " (?Intersection@R2Rect@@QEBA?AV1@AEBV1@@Z) referenced in function "void __cdecl R2Rect_Intersection_autocxx_wrapper(class R2Rect const &,class R2Rect const &,class R2Rect *)" (?R2Rect_Intersection_autocxx_wrapper@@YAXAEBVR2Rect@@0PEAV1@@Z)
          autocxx-s2-example.lib(b9f8152bc0f78e12-gen0.o) : error LNK2019: unresolved external symbol "public: bool __cdecl R2Rect::ApproxEquals(class R2Rect const &,double)const " (?ApproxEquals@R2Rect@@QEBA_NAEBV1@N@Z) referenced in function "bool __cdecl R2Rect_ApproxEquals_autocxx_wrapper(class R2Rect const &,class R2Rect const &,double)" (?R2Rect_ApproxEquals_autocxx_wrapper@@YA_NAEBVR2Rect@@0N@Z)
          C:\WS\AXP\Rust\autocxx\examples\s2\target\debug\deps\autocxx_s2_example.exe : fatal error LNK1120: 13 unresolved externals

error: could not compile `autocxx-s2-example` due to previous error

**Comment by adetaylor** [comment]
Yep - this is a known problem - https://github.com/google/autocxx/blob/main/.github/workflows/ci.yml#L123 - pull requests to fix this are welcome, but I've not investigated the cause.

**Comment by DCMinds** [comment]
@adetaylor Does that error means, it is not able to find the build library **autocxx-s2-example.lib**

**Comment by adetaylor** [comment]
I don't know what's up with this example, but I've made no attempt to build the C++ here, so I'd guess that on non-Windows platforms the required C++ code is inlined, whereas on Windows platform non-inline symbols are required.

Whatever linking problem you're getting is very probably a different cause anyway.

**Comment by DCMinds** [comment]
@adetaylor, Instead of creating a .lib file from source, create bindings and link it.
Using AutoCXX, Can we directly use already built library and create rust bindings and call the C++ api 
I mean have a C++ library and hearder files, how to link and use it in Rust?

**Comment by adetaylor** [comment]
I wrote some general information yesterday about this - https://google.github.io/autocxx/contributing.html#bugs-related-to-linking-problems - I won't be able to help with individual bugs.
