### ISSUE TITLE
Types without constructors do not gain a make_unique

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#122]
If.a struct/class has a constructor, we generate a `make_unique` associated function. We don't do that for types which have no constructors. We (probably?) should at least for non-POD types, calling the default C++ constructor.

This may be difficult depending on whether we can find out that the type has a private non-default constructor.

**Comment by adetaylor** [comment]
I've fixed up this PR, but I don't want to merge it until I've investigated the vexed issue of private constructors.

**Comment by martinboehme** [comment]
Just adding some notes here.

I think the most robust way to deal with this would be:
* Provide access to Clang's `CXXRecordDecl::needsImplicitDefaultConstructor()` in libclang (I think this isn't available today)
* Have bindgen call that API and output a suitable attribute on the generated Rust struct
* Interpret this attribute in autocxx

If libclang doesn't want to expose `needsImplicitDefaultConstructor()`, then bindgen could try to replicate the logic that governs whether a class has an implicit default constructor, but that seems potentially error-prone.

For reference, here is how Swift's C++ interop deals with this:

https://github.com/apple/swift/blob/main/lib/ClangImporter/ImportDecl.cpp#L3685
