### ISSUE TITLE
Can we Use autocxx without C++ source

### ISSUE THREAD

**Issue by DCMinds** [google/autocxx#1228]
I just went through the tutorial on how to use autocxx and its a fantastic project!

I have a static library and header files but no C++ source code. Is it still possible to use autocxx with that?
Can you please provide some sample code for build.rs

**Comment by adetaylor** [comment]
Yes, the demo project has no .cc/.cpp file file.

**Comment by adetaylor** [comment]
I'm sorry, I can't respond to each individual who has C++ linking questions. It's just too much. Please see https://google.github.io/autocxx/contributing.html#bugs-related-to-linking-problems, and if that doesn't answer your questions, please go and read up on C++ linking into Rust. It's not autocxx-specific.
