### ISSUE TITLE
autocxx-build is not on version 0.24.0

### ISSUE THREAD

**Issue by VirxEC** [google/autocxx#1230]
## Expected Behavior
Version 0.24.0 for `autocxx-build` should be published in https://crates.io/crates/autocxx-build as it's referenced in the tutorial https://google.github.io/autocxx/tutorial.html and `autocxx` is on version 0.24.0

## Actual Behavior
Only version 0.23.1 is published

## Steps to Reproduce the Problem

1. Go to https://crates.io/crates/autocxx-build/versions
2. Latest version is 0.23.1

**Comment by adetaylor** [comment]
Argh, thanks, my publishing script failed part way through. Done.
