### ISSUE TITLE
How to call rust function from c++ main()

### ISSUE THREAD

**Issue by Yogaht** [google/autocxx#1236]
I have found a sample here, but it use rust main recall c++ function. How can I call rust function directly in c++ main?
[cpp_calling_rust](https://github.com/google/autocxx/tree/main/examples/cpp_calling_rust)

I think I need a extra build system to compile c++, and link the rust staticlib/cdylib. But how to transfer the rust code and build staticlib/cdylib using autocxx and cargo, please help.

**Comment by adetaylor** [comment]
https://google.github.io/autocxx/contributing.html#bugs-related-to-linking-problems

**Comment by Yogaht** [comment]
@adetaylor Thanks for your reply, but actually I'm not talking about the c++ linking issues.
I'm trying to **call rust function directly in c++** and like this:
```
// input.cc
#include "cxxgen.h"
#include "input.h"

void hello() {
    hello_world();
}
```

```
// lib.rs
#[autocxx::extern_rust::extern_rust_function]
pub fn hello_world() {
    println!("helloworld")
}
```

```
// build.rs
fn main() -> miette::Result<()> {
    let path = std::path::PathBuf::from("src");
    let mut b = autocxx_build::Builder::new("src/lib.rs", &[&path])
        .auto_allowlist(true)
        .build()?;
    b.flag_if_supported("-std=c++17")
        .file("src/input.cpp")
        .compile("autocxx-cpp-calling-rust-example");
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/input.cpp");
    println!("cargo:rerun-if-changed=src/input.h");
    Ok(())
}
```

But get cargo run build-script-build error: 
```
error: failed to run custom build command for `autocxx_demo v0.1.0 (/home/haotuo/study/rust/cxx_call_rust/autocxx_demo)`

Caused by:
  process didn't exit successfully: `/home/haotuo/study/rust/cxx_call_rust/autocxx_demo/target/debug/build/autocxx_demo-015ff30d0d327935/build-script-build` (exit status: 1)
  --- stderr
  Error:
    × dynamic discovery was enabled but no mod was found
```

How can I solve this, Could you please help me?

**Comment by adetaylor** [comment]
Ah OK. You can't use `#[autocxx::extern_rust::extern_rust_function]` unless you also have an `include_cpp!` macro somewhere. I'm going to reopen this issue as a reminder that I need to make those diagnostics clearer.

**Comment by Yogaht** [comment]
Great! So what can I do? I think `include_cpp!` is not needed in my case because rust call c++ is not needed.

**Comment by adetaylor** [comment]
For now, `include_cpp!` is needed. It's possible I can lift that restriction in future. autocxx is primarily about Rust calling C++, not the other way round. You might be the first person ever to use it in the opposite direction only.
