### ISSUE TITLE
Missing lifetime specifier in generated code

### ISSUE THREAD

**Issue by SKyletoft** [google/autocxx#1238]
## Expected Behavior
There would be a lifetime specifier in the generated function

## Actual Behavior
Borrowchecking error
[Error log](https://gist.github.com/SKyletoft/e18061e762919b6085e2b4b7f540440e)

## Steps to Reproduce the Problem

1. Include [this](https://github.com/S2E/s2e/blob/master/libs2ecore/include/s2e/S2E.h) header
2. `generate!` the type `s2e::S2E`

[Reproduced in this repo](https://github.com/SKyletoft/s2e-autocxx-error)

## Specifications

- Version: autocxx 0.24.0, Rust 1.66.1
- Platform: Linux NixOS Unstable x64 (nixpkgs), Ubuntu 22.04 x64 (rustup)

**Comment by adetaylor** [comment]
Thanks, I'm traveling this week but I'll take a look next week. It would be even better if you could [raise a PR with a failing integration test](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs).

**Comment by adetaylor** [comment]
Thanks, yeah, autocxx-reduce (when it's working) will shrink that down to just 2-3 lines of code! However, it's quite pernickety to get working, because it has to make assumptions about your local build environment (as you noticed).

Let me see if I can reproduce it using the example repo you gave.

**Comment by adetaylor** [comment]
I can reproduce this with your provided standalone repo (thanks for doing that), I made a `repro.json` and I'm now running it through the reduction pipeline. From here on it's just a matter of time (possibly a week) until it spits out a minimized test case.

**Comment by adetaylor** [comment]
Here is the minimized test case spat out by the reduction pipeline:

```cpp
namespace a {
class b;
}
namespace s2e {
class c;
class f {
  a::b d();
};
class S2E {
public:
  f e;
  a::b &d(c *) const;
};
} // namespace s2e
```

I expect it can be trimmed down a little more by hand, but that should give me enough to work with to diagnose the problem. I'm in the middle of a few other things right now but will take a look eventually. Thanks for the report, and thanks for making it possible to get a minimal test case like this.

**Comment by adetaylor** [comment]
I think I see what's going on here.

The generated code (about which `rustc` complains) is:

```rust
pub unsafe fn S2E_d_autocxx_wrapper_0xa21e7b0ce9f73499 (autocxx_gen_this : & S2E , arg1 : * mut c) -> Pin < & mut b > ;
```

The code generator assumed that lifetimes could be elided in this case, but they can't, because the the input reference is `&` and the output reference is `&mut`. Of course, explicit lifetimes also can't help here - I think we need to reject such functions, at least until all the `CppRef` stuff enables us to move beyond normal Rust reference semantics.
