### ISSUE TITLE
RFE: Generate `cxx.h` via autocxx-gen command by an option or by default

### ISSUE THREAD

**Issue by nak3** [google/autocxx#1246]
## Expected Behavior

* Generate `cxx.h` via autocxx-gen command by an option or by default

## Actual Behavior

* `autocxxgen_ffi.h` generated by autocxx-gen requirs `cxx.h` but it cannot be generated.

### 1. Run generates cpp files by:

```
$ cd gen/cmd
$ cargo run ../../demo/src/main.rs --inc=../../demo/src  --outdir=/tmp/ --gen-cpp
```

Then, `autocxxgen_ffi.h` requires `cxx.h` which cannot be generated via another command.

## Specifications

- Version: HEAD(e47ff2eff9103781fc57e09077c599514df073a9)

## Additional info

* The command has `--cxx-h-path` and unit test creates the file "manually" so no creating `cxx.h` seems by design.

https://github.com/google/autocxx/blob/e47ff2eff9103781fc57e09077c599514df073a9/gen/cmd/tests/cmd_test.rs#L112-L113

* However, `builde.rs` creates the `cxx.h` so adding the option to autocxx-gen command is also reasonable?

https://github.com/google/autocxx/blob/e47ff2eff9103781fc57e09077c599514df073a9/engine/src/builder.rs#L203-L212

* This makes using autocxx via bazel more difficult.

**Comment by adetaylor** [comment]
I'd be happy to accept a pull request to add an additional command line option to `autocxx_gen` to create this file. (The only reason this option is present in `autocxx_build` but not `autocxx_gen` is that `autocxx_gen` was initially designed for a build system which already knew where to find `cxx.h`.)
