### ISSUE TITLE
Crash using UniquePtr with moveit

### ISSUE THREAD

**Issue by silvanshade** [google/autocxx#1265]
## Expected Behavior

Program should not be allowed to compile.

## Actual Behavior

Program compiles, and when run, crashes, without using `unsafe`.

## Steps to Reproduce the Problem

This is a follow up issue related to #1260.

I created a new issue for this here since the original issue in https://github.com/google/moveit/issues/34 did not mention the unsoundness problem with regard to the `DerefMove` impl for `UniquePtr` but only pointed out the problem for the `Pin<_>` types. Also, that issue did not directly demonstrate how the problem can lead to a program crashing.

I created a repo with a sample program at https://github.com/silvanshade/autocxx-crash, which consists of the following:

```c++
// gen.hxx

#pragma once

#include <string>

class Test
{
public:
  explicit Test(std::string string)
    : string(std::move(string))
  {
  }

  Test() = delete;

  [[nodiscard]] auto get_string() const -> std::string const& { return this->string; }

private:
  std::string string;
};
```

```rust
// gen.rs

mod gen;

use autocxx::prelude::*;
use cxx::UniquePtr;

fn main() {
    println!("start");
    run(); // crashes here
    println!("done");
}

fn run() {
    let str0 = "string";
    let str1 = "another string";
    let ptr0 = UniquePtr::emplace(gen::Test::new(str0));
    let ptr1 = UniquePtr::emplace(gen::Test::new(str1));
    println!("0: {}", ptr0.get_string());
    println!("1: {}", ptr1.get_string());
    moveit!(let mut ref0 = &move *ptr0);
    moveit!(let mut ref1 = &move *ptr1);
    println!("0: {}", ref0.get_string());
    println!("1: {}", ref1.get_string());
    println!("swap");
    core::mem::swap(&mut *ref0, &mut *ref1);
    println!("0: {}", ref0.get_string());
    println!("1: {}", ref1.get_string());
}
```

When run with `cargo run`, the program will output the following:

```
start
0: string
1: another string
0: string
1: another string
swap
0: string
1: anothe
munmap_chunk(): invalid pointer
Aborted
```

This is with no use of `unsafe` other than to mark the generated method.

The problem is essentially due to the lines (and then the subsequent call to `core::mem::swap`):

```
    moveit!(let mut ref0 = &move *ptr0);
    moveit!(let mut ref1 = &move *ptr1);
```

These should not be allowed since `Test: !Unpin` and the PRs https://github.com/google/moveit/pull/37 and #1260 should reject this during compilation.

**Comment by adetaylor** [comment]
Thanks - I'll ping re https://github.com/google/moveit/pull/37

**Comment by adetaylor** [comment]
This finally got fixed, thanks again for the report.
