### ISSUE TITLE
no template named 'optional' in namespace 'std' with -std=c++17

### ISSUE THREAD

**Issue by Omicronlawful** [google/autocxx#1280]
## What i tried to do:
I wanted to use the ctranslate library in rust. I wanted to test it so i just changed the c++ version and added the header. This causes a compiler error. It says that optional doesnt exist in std, but it should since it was added in -std=c++17.

## Expected Behavior
Shoud use ctranslate2

## Actual Behavior

  --- stderr
  /usr/local/include/ctranslate2/decoding.h:24:10: error: no template named 'optional' in namespace 'std'
  /usr/local/include/ctranslate2/generation.h:35:10: error: no template named 'variant' in namespace 'std'
  /usr/local/include/ctranslate2/generation.h:87:10: error: no template named 'optional' in namespace 'std'
  /usr/local/include/ctranslate2/translation.h:41:10: error: no template named 'variant' in namespace 'std'
  Error: 
    × the include_cpp! macro couldn't be expanded into Rust bindings to C++:
    │ Bindgen was unable to generate the initial .rs bindings for this file.
    │ This may indicate a parsing problem with the C++ headers.

## Steps to Reproduce the Problem simple
1. download demo
2. add `#include <optional>`
3. add this function: std::optional<int> try_parse_int(std::string s)
{
    //try to parse an int from the given string,
    //and return "nothing" if you fail
}
4. change c++ version to 17 or 20
## Steps to Reproduce the Problem

1. use demo
4. change c++ version to 17
5. add ctranslate2/translator.h to header file

## Specifications

- Version:"0.25.0"
- Platform: MacOS

**Comment by adetaylor** [comment]
Thanks, could you add a failing [test case like this](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs)? Or at least please give more precise steps about how you "change c++ version to 17" etc.
