### ISSUE TITLE
All subclass methods are given `void` return type

### ISSUE THREAD

**Issue by Supreeeme** [google/autocxx#1287]
Any methods in a Rust subclass have a void return type in the generated C++, regardless of what the return type actually is, leading to compilation errors. This seems to be a noted limitation from the [initial PR for subclass support.](https://github.com/google/autocxx/pull/589)

**Comment by adetaylor** [comment]
Yeah. That's no good. Even though subclass support is marked as limited and experimental, this particular restriction isn't documented — and even if it were, we should at least provide diagnostics. Thanks for the report, I'll work on it in the coming weeks if I can (possibly just to provide good diagnostics, possibly to make this more flexible)
