### ISSUE TITLE
Documentation: clarify cxx::bridge for std::vector<Type*> bindings

### ISSUE THREAD

**Issue by pkarneliuk** [google/autocxx#1301]
**Describe the bug**
Documentation (https://google.github.io/autocxx/workflow.html) does not explain how to implement the `#[cxx::bridge]` for passing vector of pointers to objects `std::vector<Type*>` from C++ to Rust. This is relatively common use-case. 

**To Reproduce**
`autocxx` can not generate bindings for std::vector of pointers to objects, like `std::vector<Type*>`

<details>
<summary>
instrument.hpp
</summary>

```shell
// instrument.hpp
#pragma once
#include <vector>

struct Instrument {
    int id;
    Instrument(int i) : id{i} {}
    virtual ~Instrument() = default;
    virtual int get() const {
        return id;
    }

    static Instrument* create(int i) {
        return new Instrument(i);
    } 
};

std::vector<Instrument*> instrument_list() {
    std::vector<Instrument*> instruments = {
        Instrument::create(1),
        Instrument::create(2),
        Instrument::create(3)
    };
    return instruments;
}
```
</details>

<details>
<summary>
lib.rs
</summary>

```shell
// lib.rs
use autocxx::prelude::*;

include_cpp! {
    #include "instrument.hpp"
    generate!("Instrument")
    generate!("instrument_list")
}
```
</details>

Generated `.rs` contains:
```shell
# [doc = "autocxx bindings couldn't be generated: Type std::vector was parameterized over something complex which we don't yet support"] 
pub struct instrument_list ; 
```
**Expected behavior**
It would be great to provide some example of `#[cxx::bridge]` when C++ code pass `std::vector<Type*>` to Rust code and methods of Type can be called from Rust side.

**Additional context**
There is the unit test[ `test_vector_of_pointers()`](https://github.com/google/autocxx/blame/main/integration-tests/tests/integration_test.rs#L5418-L5433) for similar use-case, but there is no example how to write correct `#[cxx::bridge]` for passing vector of pointers to objects.

**Comment by adetaylor** [comment]
Fundamentally, autocxx is limited to the [types supported by cxx](https://cxx.rs/binding/cxxvector.html), and I don't believe that a `CxxVector<*const T>` is supported by cxx.

About three years ago [I tried to implement this but ran out of time](https://github.com/dtolnay/cxx/issues/795) - feel free to take over that work! Once it's supported in cxx, it should be easy enough to support in autocxx too.
