### ISSUE TITLE
Type .. could not be POD because its dependent type `__BindgenBitfieldUnit` isn't known

### ISSUE THREAD

**Issue by vlad-rw** [google/autocxx#1303]
**Describe the bug**

(Again, not a C++ expert)

Trying to generate a type as POD so that it can be included in a `std::vector` of elements later. The type is complex and yields the error described.

**To Reproduce**

(Semi-minimized example from vendor library headers):

```
#[test]
fn test_cpp_union_pod() {
    let hdr = indoc! {"
        typedef unsigned long long UInt64_t;
        struct ManagedPtr_t_;
        typedef struct ManagedPtr_t_ ManagedPtr_t;
        
        typedef int (*ManagedPtr_ManagerFunction_t)(
                ManagedPtr_t *managedPtr,
                const ManagedPtr_t *srcPtr,
                int operation);
        
        typedef union {
            int intValue;
            void *ptr;
        } ManagedPtr_t_data_;
        
        struct ManagedPtr_t_ {
            void *pointer;
            ManagedPtr_t_data_ userData[4];
            ManagedPtr_ManagerFunction_t manager;
        };
        
        typedef struct CorrelationId_t_ {
            unsigned int size : 8;
            unsigned int valueType : 4;
            unsigned int classId : 16;
            unsigned int reserved : 4;
        
            union {
                UInt64_t intValue;
                ManagedPtr_t ptrValue;
            } value;
        } CorrelationId_t;
    "};

    let rs = quote! {};
    run_test("", hdr, rs, &[], &["CorrelationId_t_"]);
}
```

Yields:

```
Type CorrelationId_t_ could not be POD because its dependent type __BindgenBitfieldUnit isn't known
```

**Expected behavior**

The type can be generated as POD.

**Additional context**

This is probably difficult given the lack of a stable ABI for union support?

**Comment by adetaylor** [comment]
Thanks for this issue! Just to.let you know I am not ignoring it, and at the very least better diagnostics would be good. I just haven't got to it yet

**Comment by adetaylor** [comment]
#1313 adds better diagnostics here. I know that's not ideal, but I think that's the best we're going to be able to do any time soon. I wouldn't want to attempt to support bitfields as a POD type. Thanks for the report.

**Comment by adetaylor** [comment]
I don't know for sure, but I'd consider making a pure cxx (not autocxx) test case - can you pass around `Vec<UniquePtr<T>>` or `Vec<Box<T>>`? If that works in cxx but not autocxx, please raise a bug.
