### ISSUE TITLE
[std=c++17] Builder flag_if_supported/flag ignored

### ISSUE THREAD

**Issue by jwinarske** [google/autocxx#1304]
**Describe the bug**
Using `b.flag_if_supported("-std=c++17")` has no impact, and the log output will still use `-std=c++14`.  Same for `b.flag("-std=c++17")`

Snippet from `RUST_LOG=autocxx_engine=info cargo build` when using with `b.flag_if_supported("-std=c++17")`.  Notice `-std=c++14` in log:
```

  cargo:warning=MESSAGE:Bindgen flags would be: "--use-specific-virtual-function-receiver" "--cpp-semantic-attributes" "--represent-cxx-operators" "--use-distinct-char16-t" "--blocklist-item" "std::unique_ptr" "--blocklist-item" "std::vector" "--blocklist-item" "std::shared_ptr" "--blocklist-item" "std::weak_ptr" "--blocklist-item" "std::string" "--blocklist-item" "rust::Str" "--blocklist-item" "rust::String" "--blocklist-item" "rust::Box" "--allowlist-type" "mbgl::ffi::Context::Context" "--allowlist-type" "autocxx_make_string_0x87976c9e4c91ff15" "--allowlist-function" "mbgl::ffi::Context::Context" "--allowlist-function" "autocxx_make_string_0x87976c9e4c91ff15" "--allowlist-var" "mbgl::ffi::Context::Context" "--allowlist-var" "autocxx_make_string_0x87976c9e4c91ff15" "--default-enum-style" "rust" "--enable-cxx-namespaces" "--no-layout-tests" "--no-derive-copy" "--no-derive-debug" "--no-derive-default" "--generate" "functions,types,vars,methods,constructors,destructors" "--generate-inline-functions" "--rust-target" "1.68" "--respect-cxx-access-specs" "--" "-x" "c++" "-std=c++14" "-DBINDGEN"
... 
```

**To Reproduce**
Add `.flag_if_supported("-std=c++17")` to build.rs.  Alternatively use `.flag("-std=c++17")`

**Expected behavior**
"-std=c++17" is applied to compiler invocation instead of "-std=c++14"

**Comment by jwinarske** [comment]
If I use 
```
    let mut b = autocxx_build::Builder::new("src/lib.rs", &[...])
        .extra_clang_args(&["-std=c++17", "-Wc++17-extensions", "-Wunused-parameter"])
        .build()?;

    b.file("cxx/context.cpp")
        .compile("example");
```
it appends `"-std=c++17"` but `"-std=c++14"` is still present.

**Comment by jwinarske** [comment]
works fine.

**Comment by jwinarske** [comment]
Actually it doesn't work.  I can make it work if I patch `engine/src/lib.rs` from `"-std=c++14"` to `"-std=c++17"`.

Setting c++ version using extra_clang_args does not apply until after it's occurrence, which is at the tail of the compiler invocation.  Which doesn't affect any of the includes.

I think it might be best to allow overriding c++ version, setting default value 14.

Is there a reason it's hard coded to 14?

**Comment by adetaylor** [comment]
You're right to be using [extra_clang_args](https://docs.rs/autocxx-engine/0.26.0/autocxx_engine/struct.Builder.html#method.extra_clang_args).

Applying this diff to the code in `demo` seems to build OK for me:

```
diff --git a/demo/build.rs b/demo/build.rs
index 69c632c4..f91eae0d 100644
--- a/demo/build.rs
+++ b/demo/build.rs
@@ -8,8 +8,10 @@
 
 fn main() -> miette::Result<()> {
     let path = std::path::PathBuf::from("src");
-    let mut b = autocxx_build::Builder::new("src/main.rs", [&path]).build()?;
-    b.flag_if_supported("-std=c++14").compile("autocxx-demo");
+    let mut b = autocxx_build::Builder::new("src/main.rs", [&path])
+        .extra_clang_args(&["-std=c++17"])
+        .build()?;
+    b.flag_if_supported("-std=c++17").compile("autocxx-demo");
 
     println!("cargo:rerun-if-changed=src/main.rs");
     println!("cargo:rerun-if-changed=src/input.h");
diff --git a/demo/src/input.h b/demo/src/input.h
index b6cdd874..5cc93955 100644
--- a/demo/src/input.h
+++ b/demo/src/input.h
@@ -12,6 +12,7 @@
 #include <sstream>
 #include <stdint.h>
 #include <string>
+#include <optional>
 
 class Goat {
 public:
```

**Comment by adetaylor** [comment]
(At the very least the documentation needs to be improved here, so I'll keep this issue open. But I want to make sure you can resolve your problem first - can you try the above diff against the demo, and report back on whether it works for you?)

**Comment by jwinarske** [comment]
@adetaylor Using your suggest pattern works!  The only combo I didn't try :)

This gets me past the issue:
```
    let mut b = autocxx_build::Builder::new("src/lib.rs", &[
        &path27, &path28, &path29, &path30,
        &path1, &path2,                          &path5, &path6, &path7, &path8, &path9, &path10,
        &path11, &path12, &path13, &path14, &path15, &path16, &path17, &path18, &path19, &path20,
        &path21, &path22, &path23, &path24, &path25
        ])
        .extra_clang_args(&["-std=c++17"])
        .build()?;

    b.flag_if_supported("-std=c++17").file("cxx/context.cpp")
        .compile("autocxx-maplibre-example");
```

Yes I agree the docs need to improve around this

**Comment by adetaylor** [comment]
OK great, thank you.

**Comment by adetaylor** [comment]
There was already a test for C++17 compatibility, so I just improved the documentation here. Thanks again for the report.
