### ISSUE TITLE
Access Rust struct field from C++?

### ISSUE THREAD

**Issue by albert-tomanek** [google/autocxx#1321]
Hello, sorry I might be missing something in the docs but in the [`cpp_calling_rust`](https://github.com/google/autocxx/tree/main/examples/cpp_calling_rust) demo, if I want to access a field in an exposed Rust struct [from C++](https://github.com/google/autocxx/blob/fdfb26e26602e24466dfc506782567deb72c9a29/examples/cpp_calling_rust/src/input.cc#L12) like so:

```c++
void jurassic() {
    rust::Box<Dinosaur> prey = new_dinosaur(false);
    rust::Box<Dinosaur> predator = new_dinosaur(true);
    predator->carnivore = true;
```

By making it public in the [exposed rust type:](https://github.com/google/autocxx/blob/fdfb26e26602e24466dfc506782567deb72c9a29/examples/cpp_calling_rust/src/main.rs#L27)

```rust
#[autocxx::extern_rust::extern_rust_type]
pub struct Dinosaur {
    pub carnivore: bool,
}
```

It is not mirrored in the generated C++ header:

```c++
#ifndef CXXBRIDGE1_STRUCT_Dinosaur
#define CXXBRIDGE1_STRUCT_Dinosaur
struct Dinosaur final : public ::rust::Opaque {
  void roar() const noexcept;
  void eat(::rust::Box<::Dinosaur> other_dinosaur) noexcept;
  ~Dinosaur() = delete;

private:
  friend ::rust::layout;
  struct layout {
    static ::std::size_t size() noexcept;
    static ::std::size_t align() noexcept;
  };
};
#endif // CXXBRIDGE1_STRUCT_Dinosaur
```

Is this not supported or am I missing something?

Thanks!

**Comment by adetaylor** [comment]
Thanks, sorry for the slow response, I've been away for a while.

Indeed this is not supported. This creates a cxx [opaque Rust type as described here](https://cxx.rs/extern-rust.html#opaque-rust-types).

What you're asking for is a [shared type as described here](https://cxx.rs/shared.html), and there's currently no way to do that. I'd be open to accepting pull requests to add a `#[autocxx::extern_rust::extern_shared_type]` which I'd never thought of doing previously!
