### ISSUE TITLE
Support cxx opaque types for subclassing

### ISSUE THREAD

**Issue by rzhw** [google/autocxx#1328]
When attempting to subclass a type that refers to types that can't be automatically converted by autocxx, compile will fail:

main.h
```cpp
class MySuperType {
  public:
    virtual void DoSomething(MyUnsupportedType* foo, MySupportedType* bar) const = 0;
    virtual ~MySuperType() = default;
};
```

main.rs
```rust
include_cpp! {
    #include "main.h"
    safety!(unsafe_ffi)
    // This won't help, autocxx will still attempt to generate against the real MyUnsupportedType
    extern_cpp_opaque_type!("MyUnsupportedType", ffi2::MyUnsupportedType)
    subclass!("MySuperType", MyDerivedType)
}

#[cxx::bridge]
mod ffi2 {
    unsafe extern "C++" {
        type MyUnsupportedType;
    }
}

#[subclass]
#[derive(Default)]
pub struct MyDerivedType {}

impl ffi::MySuperType_methods for MyDerivedType {
    unsafe fn DoSomething(&self, foo: *mut ffi::MyUnsupportedType, bar: *mut ffi:MySupportedType) {
        unimplemented!("no lol")
    }
}
```

```
  Error:   × cxx couldn't handle our generated bindings - could be a bug in autocxx:
    │ unsupported type: MyUnsupportedType
```

## Expected Behavior

It could be nice to allow the above (or similar) to work, i.e. if cxx can't handle a type then allow it to be used in an opaque manner.

## Actual Behavior

Compile fails as above.

(Could this be related to https://github.com/google/autocxx/issues/1278?)

## Steps to Reproduce the Problem

See code above.

**Comment by adetaylor** [comment]
I see. Would you be kind enough to make a pull request which has a reproducible test case? (Ideally as a [new integration test](https://github.com/google/autocxx/blob/main/book/src/contributing.md#reporting-bugs) but failing that, changes to one of the existing demos/examples).
