### ISSUE TITLE
Can't recognize std::vector<int>

### ISSUE THREAD

**Issue by noy1993** [google/autocxx#1332]
**Describe the bug**
autocxx cannot recognize my **`std::vector<int>`**, but it can recognize **`std::vector<int32_t>`**. However, I want it to recognize **`int`**. What should I do?

**To Reproduce**
``` C++
std::vector<int> createVector()
{
    return std::vector<int>{1, 2, 3};
}
```

I've received a createVector struct with the following comments:
```
autocxx bindings couldn't be generated: A C++ std::vector was found containing some type that cxx can't accommodate as a vector element (int)
```

**Specifications**
* Version: `autocxx = "0.26.0"` `cxx = "1.0.107"` `rustc 1.72.0`
* Platform: windows10 x64

**Comment by adetaylor** [comment]
The situation is exactly as described in the error message. [cxx's vector type does not support `int`](https://cxx.rs/binding/cxxvector.html) so autocxx can't either.

https://github.com/dtolnay/cxx/pull/874 would fix this, but got stuck.
