### ISSUE TITLE
Feature request: be able to implement functions declared in C++ headers

### ISSUE THREAD

**Issue by russelltg** [google/autocxx#1333]
It would be cool to enable something like:

(syntax is of course just to demonstrate)

```C++
// a.h
#include <string>

namespace Hello {
    void say_hi(const std::string& i);
}
```

```Rust
// a.rs
include_cpp! {
    #include "a.h"
    #generate("Hello::say_hi");
}

#[cpp_name = "Hello::say_hi"]
fn say_hi(i: &CxxString) {
     println!("hi: {i}");
}
```

Or is it possible somehow? I've looked through the docs, if this is possible I'm happy to update docs.

**Comment by adetaylor** [comment]
Is https://docs.rs/autocxx/latest/autocxx/extern_rust/attr.extern_rust_function.html what you need?
