### ISSUE TITLE
autocxx.rs is down. Oh no!

### ISSUE THREAD

**Issue by ChieloNewctle** [google/autocxx#1399]
**Describe the bug**

[autocxx.rs](https://autocxx.rs/) is down.

**Additional context**

[https://downforeveryoneorjustme.com/autocxx.rs?proto=https](https://downforeveryoneorjustme.com/autocxx.rs?proto=https)

**Comment by adetaylor** [comment]
Thanks for the report! You know what, I think I never registered `autocxx.rs` in the first place! I've adjusted the `Cargo.toml` and other files to point to a domain which actually exists.
