### ISSUE TITLE
unable to build demo project

### ISSUE THREAD

**Issue by jeffbrn** [google/autocxx#1405]
I am looking to use some of our existing c++ libs with rust and it was suggested to try autocxx - so i have no experience with this code base.
I looked at the documentation and decided to clone this repo and try to build and run the demo code with no success.

It seems that the build fails whenever I try to include a standard library file that isn't suffixed with a '.h', specifically:
```
error: failed to run custom build command for `autocxx-demo v0.27.0 (/home/jeffb/code/tmp/autocxx/demo)`

Caused by:
  process didn't exit successfully: `autocxx/target/debug/build/autocxx-demo-69ff9bef02d85518/build-script-build` (exit status: 1)
  --- stderr
  src/input.h:11:10: fatal error: 'cstdint' file not found
  Error:   × the include_cpp! macro couldn't be expanded into Rust bindings to C++:
    │ Bindgen was unable to generate the initial .rs bindings for this file.
    │ This may indicate a parsing problem with the C++ headers.

```

If i change '#include <cstdint>' with '#include <stdint.h>' 
then that line passes and then it complains about ```<sstream>```

I then cloned cxx and built their demo and it builds and runs even though it includes ```<memory>```

I tried to skim through the documentation to see if there is anything in my environment I need to setup but nothing stood out. I am sure it is just my environment (I tried googling the problem and no one else seems to have this issue so its just me) I don't know what else to try so I hope you don't mind me raising this issue to get some help.

My Environment:
Windows 11 running WSL 2 with OS: Ubuntu jammy 22.04 x86_64
rustc: 1.82.0
clang++: Ubuntu clang version 14.0.0-1ubuntu1.1

Please let me know if there is anymore information I can provide

**Comment by adetaylor** [comment]
I don't know exactly what's up with your environment, but as you note it seems to be a problem finding the C++ headers when `autocxx` uses `bindgen` to parse the `.h` file. (Note that cxx doesn't actually parse the C++ headers, so it wouldn't run into that problem; though its demo does need to build C++ so it seems likely that you've actually got those headers somewhere). My guess is that something about the WSL2 libclang is configured to find C headers but not C++ headers for some reason.

You could try changing `demo/build.rs` where it passes `-std=c++14`; perhaps you have C++ headers for other versions of C++. You could also try renaming the `.h` file to `.hpp` in case that changes the behavior of libclang.

You could try getting extra logs [per the instructions here](https://google.github.io/autocxx/contributing.html#how-to-develop) - in particular, see if you can get the line showing the instructions that autocxx is giving to bindgen.

**Comment by sjbeskur** [comment]
@jeffbrn the demo/ builds and runs for me on Ubuntu 24.04 with no issues.  The s2/ example however, failed with the exact same error message you described but this was mainly because I didn't read the instructions and pull submodule.    

I then tested the "demo/" on my windows WSL machine and it too works as expected.  (12==12).

**Comment by jeffbrn** [comment]
Thanks for taking a look i'll have to chalk it up as 'won't work with my environment'
