### ISSUE TITLE
Cargo makes extra rebuild

### ISSUE THREAD

**Issue by xxshady** [google/autocxx#1408]
**Describe the bug**

See repro [crate](https://github.com/xxshady/autocxx-repro/tree/extra-rebuild-repro), seems like it's somehow related to `include "cxx.h"`

**To Reproduce**

See repro [crate](https://github.com/xxshady/autocxx-repro/tree/extra-rebuild-repro)

**Expected behavior**

No extra rebuild

**Comment by adetaylor** [comment]
Thanks, this doesn't happen in my environment:

```
adetaylor@adetaylor /t/autocxx-repro (main)> cargo build
   Compiling repro v0.1.0 (/tmp/autocxx-repro)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.84s
adetaylor@adetaylor /t/autocxx-repro (main)> cargo build
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.07s
```

so you'll need to diagnose it a bit more to see what's different in yours. I'd pay attention to the `cargo:rerun-if-changed` lines emitted by the build script.

**Comment by adetaylor** [comment]
Only Linux, I don't have ready access to a Windows box.
