### ISSUE TITLE
std::string return types need to be unwrapped for use

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#142]
```c++
std::string my_function();
```

```rust
let s = my_function();
println!("Result is: {}", s.as_ref().unwrap().to_str().unwrap());
```

The first `as_ref().unwrap()` is required because `s` is secretly a `UniquePtr<CxxString>`. Yet, `autocxx` knows that it will never be null, so that verbosity should not be required.

We should either:
* See if we can construct a `rust::Box<std::string>` instead within C++ ([ref](https://cxx.rs/binding/box.html)). We would do this by adding a new alternative to `ArgumentConversionType`, then using it in some of the cases where we currently call `ArgumentConversionType`. But I don't know for sure whether `rust::Box<std::string>` is valid in `cxx` - that'd be the first thing to check.
* If not, construct a newtype wrapper `NotNullUniquePtr` which is returned by such functions, and dereferences to a `T` instead of an `Option<T>`. This would wrap `UniquePtr` and just `unwrap()` it on deref. Such a type would go into `src/lib.rs`. But it probably means we'd need to have a Rust-side wrapper for the `cxxbridge` function, which we don't currently do unless it's a method impl (`foreign_mod_converter::generate_method_impl`).

**Comment by dtolnay** [comment]
> If not, construct a newtype wrapper `NotNullUniquePtr` which is returned by such functions, and dereferences to a `T` instead of an `Option<T>`. This would wrap `UniquePtr` and just `unwrap()` it on deref.

UniquePtr already does unwrap on deref. https://github.com/dtolnay/cxx/blob/7297d74fd0bc61dab74d76226ba43a2e64c72212/src/unique_ptr.rs#L121-L133

There is some remaining design work on unique_ptr nullability being tracked in https://github.com/dtolnay/cxx/issues/115.

**Comment by adetaylor** [comment]
Ooh, so it does! Thanks! No action needed here then.
