### ISSUE TITLE
Support different C++ versions

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#209]
`make_bindgen_builder` currently hard-codes C++ versions.

**Comment by adetaylor** [comment]
The hard-codedness is currently [here](https://github.com/google/autocxx/blob/main/engine/src/lib.rs#L136)

**Comment by martinboehme** [comment]
The hard-coded default args that autocxx currently passes to Clang are

```
-x c++ -std=c++14 -DBINDGEN
```

IIUC, the only one of these that we might not always want is the one related to the C++ version (`-std=c++14`), correct?

I'm planning to add a feature that would allow passing arbitrary Clang arguments on the autocxx_gen command line after a `--` argument. bindgen allows exactly the same thing, so this would be consistent with that. I would also add a parameter to `autocxx_build::build`to allow passing arbitrary extra arguments.

These extra arguments could be used to specify the desired C++ version. I initially thought that I should scan the extra arguments to see if there's a `-std` argument in there and, if so, remove it from the default arguments. However, this is complicated a bit by the fact that this argument can take multiple forms (`-std=<arg>`, `--std=<arg>`, or `--std <arg>`).

Some experimentation reveals that if there are multiple `-std` arguments on the C++ command line, the last one is the one that actually has an effect. So if I make sure that the default `-std` argument goes before the extra arguments, a `-std` in the extra arguments would override the default. This behavior isn't documented anywhere, but I think it's OK to rely on for now: I think it's unlikely to change, and if it breaks, the breakage will be obvious and easy to fix. WDYT?
