### ISSUE TITLE
Assuming too high alignment of opaque types

### ISSUE THREAD

**Issue by dtolnay** [google/autocxx#26]
The last commit of #25 missed the #\[repr(C, packed)\] attribute from my link. Without that, autocxx is producing opaque types that are something like:

```rust
struct Opaque {
    do_not_attempt_to_allocate_nonpod_types: [*const u8; 0],
}
```

which has alignment of 8 (or 4).

If the real alignment of the C++ type is smaller and a reference is returned from C++ to Rust, mere existence of an insufficiently aligned reference in Rust causes UB even if never dereferenced by Rust code (see https://doc.rust-lang.org/1.47.0/reference/behavior-considered-undefined.html). Rustc can use least-significant bits of the reference for other storage.

**Comment by adetaylor** [comment]
I didn't overlook it, but I was going to spend some time figuring out what it was for. You have saved me a bunch of time, thank you.
