### ISSUE TITLE
Crate fails to build on Windows

### ISSUE THREAD

**Issue by Bromeon** [google/autocxx#27]
Unfortunately, `autocxx` fails to build on Windows, due to compile errors in the dependency osstrtools.

Steps to reproduce:

```
cargo new autocxx-example
cd autocxx-example
cargo add autocxx
cargo build
```

Errors:
```
   ...
   Compiling humantime v1.3.0
   Compiling indoc v1.0.3
   Compiling osstrtools v0.2.2
error[E0432]: unresolved import `os_str_bytes`
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\osstrtools-0.2.2\src\lib.rs:679:13
    |
679 |         use os_str_bytes::OsStringBytes;
    |             ^^^^^^^^^^^^ use of undeclared type or module `os_str_bytes`

error[E0432]: unresolved import `os_str_bytes`
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\osstrtools-0.2.2\src\lib.rs:686:13
    |
686 |         use os_str_bytes::OsStringBytes;
    |             ^^^^^^^^^^^^ use of undeclared type or module `os_str_bytes`

error[E0432]: unresolved import `os_str_bytes`
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\osstrtools-0.2.2\src\lib.rs:742:13
    |
742 |         use os_str_bytes::OsStrBytes;
    |             ^^^^^^^^^^^^ use of undeclared type or module `os_str_bytes`

error[E0405]: cannot find trait `WinOsStr` in this scope
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\osstrtools-0.2.2\src\lib.rs:740:6
    |
740 | impl WinOsStr for OsStr {
    |      ^^^^^^^^ not found in this scope

error[E0425]: cannot find value `bytes` in this scope
   --> ~\.cargo\registry\src\github.com-1ecc6299db9ec823\osstrtools-0.2.2\src\lib.rs:754:19
    |
754 |         unsafe { (bytes as *const _).cast:() }
    |                   ^^^^^                  - help: maybe you meant to write a path separator here: `::`
    |                   |
    |                   not found in this scope

error: aborting due to 5 previous errors
```

[I reported the issue at the osstrtools's repo](https://github.com/rabite0/osstrtools/issues/1#issuecomment-707376482), however the crate seems a bit abandoned.

At a first look, I could only find `split()` from that crate being used: https://github.com/google/autocxx/blob/49c8fb8d729d8688c8cb4d0c5eb5bd96bf7e0bcd/engine/src/lib.rs#L207
Is it maybe an option to get that functionality without that crate, or use an alternative?

**Comment by adetaylor** [comment]
Thanks for the report! I will figure out a way to remove that dependency once I get a few other things off my plate.

I would be _shocked_ if this builds under Windows even after this is fixed. I anticipate that a load of `bindgen` configuration is necessary which isn't currently possible with the limited interface exposed by `autocxx`. (There's the `AUTOCXX_INC` environment variable to set an include path, but currently no other way to configure `bindgen` at all. It's my intention eventually that there are richer facilities here.)
