### ISSUE TITLE
Create more comprehensive demo example

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#271]
At the moment, the `demo` directory is very basic.

We should add a `demo_complex` directory which uses some realistic pre-existing C++ codebase. `or-tools` might be a good candidate.

**Comment by GavinRay97** [comment]
I'm interested in understanding if/how I can use this with an existing CMake C++ project.

Would I take my `build.rs` which uses the `cmake` crate and replace it (I only really want to call methods from a single header in the C++ library, it's a git submodule in the project) or how exactly does it work?

This would definitely be super appreciated -- thank you! 🙏

**Comment by adetaylor** [comment]
Is the project (at least the C++ parts) open source? If it's a simple submodule that might be a really good demo example... Happy to take a look if you can send me links.

I should warn you that I find new and exciting bugs in nearly any C++ project that I throw at autocxx right now. It's not yet battle-hardened. So expect me to have to do a certain amount of work before it springs into life.

Meanwhile as to how it works, you have to arrange to run some code generation phase on the `.rs` file - and feed it the path to your C++ headers. This will output another `.rs` file which then gets `include!`ed by the `autocxx-macro` at Rust build time.

The code generation phase can either be done by `autocxx-build` (in a `build.rs`) or `autocxx-gen` (command line utility). Diagram here: https://docs.rs/autocxx/0.5.1/autocxx/macro.include_cpp.html

**Comment by GavinRay97** [comment]
Sure it's open source -- but it's niche (it builds a dynlib that's a plugin loaded by a music production DAW, that exposes ImGui to it's scripting languages so people can script their own GUI's with ImGui for doing stuff) so I am not sure it's very test-friendly =(

I currently have a `build.rs` which looks like this:
```rust
use cmake;
// You're on your own if you're not on Windows for now, sorry lol.
#[cfg(windows)]
fn main() {
    // Builds the project in the directory located in `reaimgui`, installing it into $OUT_DIR
    let dst = cmake::Config::new("reaimgui")
        .generator("Ninja")
        .very_verbose(true)
        .env("VCPKG_ROOT", "C:\\Users\\rayga\\Projects\\vcpkg")
        .env("VCPKG_DEFAULT_TRIPLET", "x64-windows-static")
        .define(
            "CMAKE_TOOLCHAIN_FILE",
            "C:/Users/rayga/Projects/vcpkg/scripts/buildsystems/vcpkg.cmake",
        )
        // Ref: https://github.com/microsoft/vcpkg/issues/11247#issuecomment-625754052
        .define("VCPKG_TARGET_TRIPLET", "x64-windows-static")
        .build();

    // ReaImGui puts it's .lib, .dll, and .pbd etc files inside of out/build/src
    println!("cargo:rustc-link-search=native={}/build/src", dst.display());
    // This is supposed to link the generated/compiled .lib file
    println!("cargo:rustc-link-lib=dylib=reaper_imgui-x64");
}
```

But I'm not sure if the last two lines are even correct (I'm a complete novice at systems programming, know basically zero Rust/C++ or how this binary/library/system stuff works).

`reaimgui` is in the project from here, this particular branch is needed because it exposes a method required: https://github.com/cfillion/reaimgui/tree/naked-ctx

I apologize in advance because this is going to get super niche and off the wall.
If you want to stop reading here and tell me "Lol sorry kid - tl;dr" I wouldn't blame you.

----

- This music DAW (REAPER) has scripting languages.
- It also has a native C++ SDK for building extensions and registering new methods for the scripting languages 		 
   - (Lua, Python)
- As you can imagine, in a single Lua script, the return value of one function call might be fed as an argument to another function, and they both might come from `dylib` of separate languages. IE:
	- ```lua
		local cpp_val = reaper.Addon_Function_From_CPP_Extension(foo)
		local rust_val_using_cpp_val = reaper.Addon_Function_From_Rust_Extension(cpp_val)
	 ```
- Someone has been porting and expanding the C++ SDK to Rust: https://github.com/helgoboss/reaper-rs
- You can register plugin methods like this:
	- https://gist.github.com/GavinRay97/e6a76d3eb870f14fa2019532e7b04d9e
		- ![image](https://user-images.githubusercontent.com/26604994/111673558-797c7600-87f1-11eb-966f-fe54af8cb7e3.png)
- The `ctx` variable used here in Lua maps to the C++ `ReaImGui` extension `Context` class
	- https://github.com/cfillion/reaimgui/blob/0753cb28e26bf928c6570b576bfd5680b80c1a01/src/context.hpp
	- ![image](https://user-images.githubusercontent.com/26604994/111672141-08888e80-87f0-11eb-97c3-f966711a99a1.png)
- In Rust, the type of my extension function has to be `*mut *mut c_void`, but I know it is actually an instance of `Context`. So I want to somehow tell this to Rust, so that I can call `Context.imgui()` to get `*ImGuiContext` and use that with `imgui-rs`
	- https://github.com/cfillion/reaimgui/blob/0753cb28e26bf928c6570b576bfd5680b80c1a01/src/context.hpp#L63
	- ```rust
	  // I want to tell it ctx is Context.hpp so I can call Context.imgui() and use that with imgui-rs to call igSetCurrentContext
	  extern "C" fn imgui_rs_test(ctx: *mut c_void, text: *mut c_void) {
	     // Here you have access to ctx variable and text passed
	  }
	  ​
	  unsafe extern "C" fn imgui_rs_test_vararg(
	      _arglist: *mut *mut c_void,
	      _numparms: c_int,
	  ) -> *mut c_void {
	      let args = std::slice::from_raw_parts(_arglist, _numparms.try_into().unwrap());
	      imgui_rs_test(args[0], args[1]);
	      null_mut()
	  }
	  ```
----

So I guess my question is -- I just want `ctx: *mut *mut c_void` to be `C++ Context.hpp` so I can call one damn method on it, what do I need to do?

🙏 

Willing to pay for an answer + explanation on this, too, because I've been beating my skull against trying to understand how all of this works for days just to do this.

**Comment by GavinRay97** [comment]
So I actually seem to have gotten most of the way there, with this:
```rust
use std::path::Path;
pub fn main() {
    let path = std::path::PathBuf::from("src").canonicalize().unwrap();
    let mut build = autocxx_build::build(
        "src/lib.rs",
        &[
            &path,
            Path::new("C:\\Users\\rayga\\Projects\\reaimgui-naked-ctx-rust\\reaimgui\\src"),
            Path::new("C:\\Users\\rayga\\Projects\\reaimgui-naked-ctx-rust\\reaimgui\\vendor"),
        ],
    )
    .unwrap();
    build.flag_if_supported("-std=c++17").compile("reaper_imgui_interop_64");
}
```

But I get this:
```
Caused by:
  process didn't exit successfully: `C:\Users\rayga\Projects\reaimgui-naked-ctx-rust\target\debug\build\reaimgui-naked-ctx-rust-e209ccc477b532da\build-script-build` (exit code: 101)
  --- stderr
  C:\Users\rayga\Projects\reaimgui-naked-ctx-rust/../reaimgui/src/color.hpp:44:17: error: no member named 'apply' in namespace 'std'
  C:\Users\rayga\Projects\reaimgui-naked-ctx-rust/../reaimgui/src/color.hpp:44:17: error: no member named 'apply' in namespace 'std', err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(MacroParseFail(Bindgen(())))', build.rs:33:6
```

Seems this is the problem:
`error: no member named 'apply' in namespace 'std'`

`std::apply` is C++ 17 but I pass `-std=c++17`. I think it might be ignoring this and using a different version?

**Comment by GavinRay97** [comment]
That worked! I just changed `-std=c++20` and deleted `Cargo.lock` + ran `cargo build`.

But from this little include:
```rust
use autocxx::include_cpp;

include_cpp! {
    #include "../reaimgui/src/context.hpp"
    safety!(unsafe_ffi)
    generate!("Context")
}

pub fn main() {
    let a = ffi::base::Context::make_unique("title", 0, 0, 0, 0);
    return ();
}
```

It wound up traversing and trying to generate almost the entire MSVC + Windows SDK 😨 
I think I need to have scoped it to a single method

Here's a gist of what it tried to watch/include, has the file list of it traversing dependency graph:
- https://gist.github.com/GavinRay97/a8434d73825e677a2fa0ced7768460a6

Also, here was the error output
```
[reaimgui-naked-ctx-rust 0.1.0] Ignored item discovered whilst parsing: autocxx does not yet know how to support the built-in C++ type std::os::raw::c_ulonglong - please raise an issue on github
[reaimgui-naked-ctx-rust 0.1.0] Ignored item discovered whilst parsing: autocxx does not yet know how to support the built-in C++ type std::os::raw::c_longlong - please raise an issue on github
[reaimgui-naked-ctx-rust 0.1.0] Ignored item discovered whilst parsing: autocxx does not yet know how to support the built-in C++ type std::os::raw::c_void - please raise an issue on github
[reaimgui-naked-ctx-rust 0.1.0] Ignored item discovered whilst parsing: autocxx does not yet know how to support the built-in C++ type std::option::Option - please raise an issue on github

[reaimgui-naked-ctx-rust 0.1.0] thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: UnexpectedForeignItem', C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\conversion\parse\parse_bindgen.rs:114:29
[reaimgui-naked-ctx-rust 0.1.0] stack backtrace:
[reaimgui-naked-ctx-rust 0.1.0]    0: std::panicking::begin_panic_handler
[reaimgui-naked-ctx-rust 0.1.0]              at /rustc/b122908617436af187252572ed5db96850551380\/library\std\src\panicking.rs:493
[reaimgui-naked-ctx-rust 0.1.0]    1: core::panicking::panic_fmt
[reaimgui-naked-ctx-rust 0.1.0]              at /rustc/b122908617436af187252572ed5db96850551380\/library\core\src\panicking.rs:92
[reaimgui-naked-ctx-rust 0.1.0]    2: core::option::expect_none_failed
[reaimgui-naked-ctx-rust 0.1.0]              at /rustc/b122908617436af187252572ed5db96850551380\/library\core\src\option.rs:1300
[reaimgui-naked-ctx-rust 0.1.0]    3: core::result::Result<tuple<>, autocxx_engine::conversion::api::ConvertError>::unwrap<tuple<>,autocxx_engine::conversion::api::ConvertError>   
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:1037
[reaimgui-naked-ctx-rust 0.1.0]    4: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_mod_items
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\conversion\parse\parse_bindgen.rs:114       
[reaimgui-naked-ctx-rust 0.1.0]    5: autocxx_engine::conversion::parse::parse_bindgen::ParseBindgen::parse_items
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\conversion\parse\parse_bindgen.rs:74        
[reaimgui-naked-ctx-rust 0.1.0]    6: autocxx_engine::conversion::BridgeConverter::convert
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\conversion\mod.rs:90
[reaimgui-naked-ctx-rust 0.1.0]    7: autocxx_engine::IncludeCppEngine::generate
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\lib.rs:414
[reaimgui-naked-ctx-rust 0.1.0]    8: autocxx_engine::parse_file::ParsedFile::resolve_all
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\parse_file.rs:125
[reaimgui-naked-ctx-rust 0.1.0]    9: autocxx_engine::builder::build_to_custom_directory<str,[std::path::Path*; 3]*,std::path::Path**>
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\builder.rs:136
[reaimgui-naked-ctx-rust 0.1.0]   10: autocxx_engine::builder::build<str,[std::path::Path*; 3]*,std::path::Path**>
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-engine-0.5.1\src\builder.rs:75
[reaimgui-naked-ctx-rust 0.1.0]   11: autocxx_build::build<str,[std::path::Path*; 3]*,std::path::Path**>
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.cargo\registry\src\github.com-1ecc6299db9ec823\autocxx-build-0.5.1\src\lib.rs:33
[reaimgui-naked-ctx-rust 0.1.0]   12: build_script_build::main
[reaimgui-naked-ctx-rust 0.1.0]              at .\build.rs:25
[reaimgui-naked-ctx-rust 0.1.0]   13: core::ops::function::FnOnce::call_once<fn(),tuple<>>
[reaimgui-naked-ctx-rust 0.1.0]              at C:\Users\rayga\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
[reaimgui-naked-ctx-rust 0.1.0] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: failed to run custom build command for `reaimgui-naked-ctx-rust v0.1.0 (C:\Users\rayga\Projects\reaimgui-naked-ctx-rust)`
```

**Comment by adetaylor** [comment]
Thanks very much for posting that and for the work required to get that far :)

The inability to configure C++ versions is #209. The `UnexpectedForeignItem` is _probably_ #262.

However: I've got to say I think you should just use `cxx` not `autocxx` in this case. I think `autocxx` is overkill if you want to just call one function:

> I guess my question is -- I just want ctx: *mut c_void to be C++ Context.hpp so I can call one damn method on it, what do I need to do?

I think here's what you should do.

* Use the pointers branch of `cxx` from here: https://github.com/dtolnay/cxx/pull/689
* Write something like this at the top of your .rs file:

```rust
#[cxx::bridge]
mod ffi {
  include!("context.hpp")
  extern "C++" {
     type Context;
     type ImGuiContext;
     fn imgui(self: &Context) -> *mut ImGuiContext;
  }
}
```
(that's unlikely to be exactly right but hopefully nudges you in the right direction)

* Copy build script steps from the [cxx demo](https://github.com/dtolnay/cxx/blob/master/demo/build.rs)
* Do something like this:
```rust
let my_ctx = unsafe { cxx::UniquePtr::from_raw( /* pass your reaper context here */ } };
let imgui_ctx = my_ctx.imgui(); // imgui_ctx _should_ be the pointer you need...
```

`autocxx` is designed to write the stuff in the second step automatically, but it looks to me like you just don't need that complexity. Good luck!

**Comment by GavinRay97** [comment]
Thank you, I genuinely appreciate it!!

I never would have known about the pointers branch of `cxx` or how to have structured it, I can't thank you enough 🙏

**Comment by adetaylor** [comment]
Previous or-tools work is in #260.

**Comment by adetaylor** [comment]
An example is going to land in #350 using `s2` and will mark this as Fixed.

Other candidates for further examples which may be worth adding in future:
* `chromium`
* `or-tools` (as discussed in #260 mostly)
* The `reaper` or `imgui` stuff discussed in this issue

**Comment by GavinRay97** [comment]
@adetaylor Woo, awesome! 🎉 🥳

**Comment by adetaylor** [comment]
It isn't, but it didn't seem to be necessary: the (very very basic) demo example therefore presumably relies only on `inline` C++ functions so there's no need to build `s2` at all. (I haven't checked that's true, but that's my assumption - I too was a bit surprised it Just Worked)
