### ISSUE TITLE
Notes on making rust-analyzer autocomplete work

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#294]
Rust-analyzer autocomplete doesn't currently work smoothly for things in the `ffi` mod because [attribute proc macros are not supported by rust-analyzer yet](https://github.com/rust-analyzer/rust-analyzer/issues/6029), so it can't expand the `cxx::bridge` mod.

An alternative would be if `cxx-gen` exposed an API to turn a `TokenStream` with a `#[cxx::bridge]` inside it into a fully expanded `TokenStream` as the macro would otherwise do. This feels like something we wouldn't want to try to upstream into `cxx` (it's quite invasive) but I am experimenting with this here:

https://github.com/dtolnay/cxx/compare/master...adetaylor:expandable

in order to find out whether there are other obstacles to `rust-analyzer` autocomplete.

**Comment by adetaylor** [comment]
It works!

You simply need:
dtolnay/cxx@master...adetaylor:expandable
https://github.com/google/autocxx/compare/expandable

Gross hacks. Not going to end up in merges or pull requests. But good for playing around.

**Comment by jnicholls** [comment]
Good deal!

**Comment by kcking** [comment]
It looks like these patches have fallen stale. I tried my hand at updating them
https://github.com/dtolnay/cxx/compare/master...kcking:master
https://github.com/google/autocxx/compare/main...kcking:main

but end up getting  
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidCxx(NoBridgeMod)', demo/build.rs:17:68
```
when running `cargo test --workspace` inside of `autocxx`.

Maybe someone else can spot what's wrong with my changes :)

**Comment by adetaylor** [comment]
Fixed - I pushed new versions to

https://github.com/dtolnay/cxx/compare/master...adetaylor:expandable
https://github.com/google/autocxx/compare/expandable

You missed one line of change, because it moved. We need to pass the `#[cxx::bridge]` mod into cxx's C++ code generation phase. In the main branch, we pass in the final .rs that `autocxx` produces. But in the `expandable` branch, that final .rs no longer has a `#[cxx::bridge]` mod (because it's been expanded to the final final Rust). We therefore squirrel away a pre-expansion version, and that's what we pass into `cxx_gen`. The place where we call into `cxx_gen` is different in modern versions of autocxx, so I had to update a different location.

**Comment by adetaylor** [comment]
Of course what we should really be doing is helping out with https://github.com/rust-analyzer/rust-analyzer/issues/6029 instead of working around its absence :) Sounds like it's in progress though - https://github.com/rust-analyzer/rust-analyzer/issues/8971

**Comment by kcking** [comment]
Hey thank you that worked!! I'm so stoked for when rust-analyzer fixes attribute proc macros. I think it prevents wasm_bindgen autocompletion currently as well.

Also thanks for the awesome tool! Currently using it with libwebrtc (and some hand-written c++ in between).

**Comment by adetaylor** [comment]
Cool, thanks for letting me know :)
