### ISSUE TITLE
DidNotGenerateAnything("Bob"))

### ISSUE THREAD

**Issue by ncnnnnn** [google/autocxx#371]
## Expected Behavior
get ffi::base::Bob

## Actual Behavior
ParseError(AutocxxCodegenError(Conversion(DidNotGenerateAnything("Bob"))))'

## Steps to Reproduce the Problem

1.clone and cargo build example ok
2.add new bob.h at ./src and add #include <string>

```
#include <string>
namespace base {
  class Bob {
  public:
      Bob(std::string name);
      void do_a_thing() const;
  };
}
```

3. main.rs add
```
 #include "bob.h"
    generate!("Bob")
```
4.out 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError(AutocxxCodegenError(Conversion(DidNotGenerateAnything("Bob"))))'
```
## Specifications

- Version:autocxx-build = "0.5.4"
- Platform:ubuntu 18.04

**Comment by adetaylor** [comment]
Try `generate!("base::Bob")` as opposed to `generate!("Bob")`.

**Comment by ncnnnnn** [comment]
ok!

also add #ifndef BOB_H_ .. #endif .. thanks!
