### ISSUE TITLE
Remove remove_ignored

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#383]
#288 introduced an analysis pass to remove ignored things (as reported in #288). I think 

I think #363 fixed the root cause, so we should revert #288.

**Comment by martinboehme** [comment]
I think this may still be needed -- see draft PR https://github.com/google/autocxx/pull/393 for an example where it's necessary to ignore APIs that use other ignored APIs.

**Comment by adetaylor** [comment]
Turns out you were right all along - see #453! :)

**Comment by martinboehme** [comment]
Interesting! That was entirely down to luck, not insight on my part though. ;)
