### ISSUE TITLE
Error building example: `cannot infer type for type parameter `impl AsRef<str>` declared on the function `build``

### ISSUE THREAD

**Issue by GavinRay97** [google/autocxx#395]
![image](https://user-images.githubusercontent.com/26604994/115627225-9f070e80-a2cc-11eb-9a99-686543dce5da.png)
```rust
pub fn build<P1, I, T>(
    rs_file: P1,
    autocxx_incs: I,
    definitions: &[impl AsRef<str>],
) -> Result<BuilderBuild, BuilderError>
where
    P1: AsRef<Path>,
    I: IntoIterator<Item = T>,
    T: AsRef<OsStr>,
{
```
https://github.com/google/autocxx/blob/main/examples/s2/build.rs#L21

**Comment by GavinRay97** [comment]
Oh it just needs an empty string like `&[&""]`

**Comment by adetaylor** [comment]
Yeah, there was a breaking change between `autocxx-build` 0.5.4 and 0.6.0. If you update to 0.6.0, this problem should go away. Let me know if not!

**Comment by GavinRay97** [comment]
Yeah that was my mistake, apologies!
