### ISSUE TITLE
Slight cleanups to #398

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#399]
There are a few things in #398 which could probably be improved:

* We should reject `rust::` types as well (some will eventually become supported by #199, but when they're added to `known_types`, the error generation in #398 will automatically become inactive)
* We're rejecting all these types because they're _broken_ because we're adding them to the `bindgen` blocklist. That being the case, we should probably generate these errors based on that very same blocklist. This _might_ require the `regex` crate but I'm pretty sure that's in the hierarchy of deps anywhere somewhere, or we could generate both lists from a common source.

**Comment by martinboehme** [comment]
> * We're rejecting all these types because they're _broken_ because we're adding them to the `bindgen` blocklist. That being the case, we should probably generate these errors based on that very same blocklist.

SGTM. FWIW, this was what I assumed the intent was when I encountered this code.
