### ISSUE TITLE
Don't generate `make_unique()` methods for abstract classes

### ISSUE THREAD

**Issue by martinboehme** [google/autocxx#424]
autocxx currently generates `make_unique()` methods for abstract classes. The C++ code for these fails to compile with an error message "invalid new-expression of abstract class type".

Here is an example of a class that fails in this way:

```cxx
class A {
public:
    A();
    virtual void foo() const = 0;
};
```

I'll shortly be submitting a PR with a failing test.

**Comment by martinboehme** [comment]
Failing test in https://github.com/google/autocxx/pull/425.

**Comment by adetaylor** [comment]
_Hmm_. This feels like a regression - I'm pretty sure autocxx used to do this right. I must have failed to add an adequate regression test, so thanks!
