### ISSUE TITLE
Multiple ignored overloads cause compilation failure

### ISSUE THREAD

**Issue by martinboehme** [google/autocxx#428]
If multiple overloads of a function are ignored, the resulting Rust code fails to compile. Here is an example:

```cxx
struct Blocked {};
class A {
public:
    void take_blocked(Blocked);
    void take_blocked(Blocked, int);
};
```

If the `Blocked` struct is blocked using the `block!` macro, this causes both `take_blocked` overloads to be ignored. For each overload, autocxx inserts a placeholder function in the generated Rust code with documentation that explains why the function was ignored. Unfortunately, both placeholder functions use the same name `take_blocked`, so the code fails to compile with a duplicate definition error.

To solve this, we should use same approach as if we had generated a valid import for the function, namely append a numerical suffix to overloads.

I will shortly submit a PR with a failing test.

**Comment by martinboehme** [comment]
Failing test in https://github.com/google/autocxx/pull/429.

**Comment by adetaylor** [comment]
Ooh, good spot.
