### ISSUE TITLE
binding to a project composed of multiple libraries

### ISSUE THREAD

**Issue by ekg** [google/autocxx#533]
We would like to wrap a library (https://github.com/jltsiren/gbwt/) which depends on another library that we typically build independently and link against (https://github.com/vgteam/sdsl-lite).

With cmake or make it's possible to script this out to support resolution of the includes in a directory in our build tree. However, I'm a little confused about how to configure autocxx to do something similar.

The provided example makes clear how things work when we're just wrapping a monorepo that contains all the C++ code. However, it's not clear how one might extend this to a case like ours with a target source tree and another that it depends on.

We are thinking of merging the two repos together so that the includes all point to headers local to the source tree. This is clunky but shouldn't be too bad. I'd like to understand if there is a better way that might let us leave both trees in their upstream state.

**Comment by adetaylor** [comment]
Hi, are you using Cargo? If so, assuming your `build.rs` is using `autocxx-build`, then presumably you just need to specify multiple include directories in the `autocxx_incs` parameter within your `build.rs`:

https://docs.rs/autocxx-build/0.8.0/autocxx_build/fn.expect_build.html

(I'd certainly accept pull requests to improve documentation here!)

If that's not good enough, could you be a bit more specific about what goes wrong?

As the Big Hammer you can switch from using `autocxx-build` to `autocxx-gen`, a command-line tool which can be used to do all the code generation. But hopefully you won't need to.

**Comment by ekg** [comment]
There is another conceptual issue that I'm struggling with. Maybe it could also be explained in the docs, but it could simply be a gap in my knowledge. How does autocxx work with static and dynamic libraries? Including the header files is clear, but I haven't caught how to work with precompiled libraries, or even if this is possible. Also, if this is possible, how do we indicate where to look for libs / which ones to link with?

**Comment by adetaylor** [comment]
Sorry for the slow reply here - I missed your e-mails before I went on vacation.

Are you using cargo for your build process? If so, the C++ build is handled by the CC crate: https://crates.io/crates/cc

**Comment by subwaystation** [comment]
I am also having the same general problem. I want to create bindings for https://github.com/pangenome/odgi similar to its python bindings https://github.com/pangenome/odgi/blob/master/src/pythonmodule.cpp. Your examples provide a great start, but if I simply add `#include odgi.hpp` to the wrapper header file, the odgi header file is obviously not found. When hardcoding the path to the odgi header file, other complaints pop-up,  telling me that I am missing other header files which `odgi.hpp` depends on.
1. I already have the whole odgi library pre-compiled. So I have `libodgi.a` and `libodgi.so`. My expectation would be that all I need to do is somehow tell the compiler in `build.rs` that it should use this library and infer the `odgi.hpp` from it. Is that possible with autocxx?
2. Or is this something I would have to do with CC? Do you have a minimal example?
3. I could put my code example somewhere, if it helps to better understand the problem. 

Thanks for any feedback!

**Comment by adetaylor** [comment]
@subwaystation in your `build.rs` file you provide a list of possible include paths to `autocxx_build::Builder::new` (it's the second parameter). Make sure all possible include directories are in there. Unfortunately in C++ there is no way to infer the include path from the library.

**Comment by subwaystation** [comment]
So I would have to include hardcoded paths to all of the headers listed in https://github.com/pangenome/odgi/blob/6a82cf30f8ff034e205f5a983784145756bd2391/CMakeLists.txt#L524?

**Comment by adetaylor** [comment]
No, you just need to provide a list of the root directories from which the include path starts. [Here's a good place to start reading up on include paths.](https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html)
