### ISSUE TITLE
Best way to write manual bindings for unimplemented types

### ISSUE THREAD

**Issue by zkjanus** [google/autocxx#565]
> It's now at the point where it works for some use-cases. If you choose to use autocxx you should expect to encounter a selection of problems, but some of your APIs will be usable. For others (e.g. those using arrays) **you'll need to write manual bindings**.

Can you elaborate a bit on how writing manual bindings within a autocxx build, using build.rs and autocxx_build::build as in the example project in this repository, _should_ be done? For unimplemented types like `std::array`.

So what I've done so far is to create a separate ffi using `#[cxx::bridge]`, but it seems it's not possible to use another FFI as a type in CXX (which is an unsupported type for UniquePtr). Should I wrap the ffi type for the UniquePtr maybe? Or is there a way to manually bind types created with autocxx within a #[cxx::bridge].  I don't understand how to best use both autocxx and cxx when needed.  I don't _think_ I need to reimplement the types autocxx generates within a `#[cxx::bridge]` ?

```
  include_cpp! {
      #include "bitcoin/system.hpp"
      safety!(unsafe_ffi)
      generate!("libbitcoin::system::to_chunk")
      generate!("libbitcoin::system::data_chunk")
      generate!("libbitcoin::system::pseudo_random_fill")
  
      // This type relies on std::array so I have to manually implement it below.
      //generate!("libbitcoin::system::wallet::hd_private")
      generate!("libbitcoin::byte_bits")
  }
  #[cxx::bridge]
  mod bcffi {
      unsafe extern "C++" {
          include!("bitcoin/system.hpp");
          include!("helpers.hpp");
          #[namespace = "libbitcoin::system::wallet"]
          type hd_private;
  
          // Add a new function in C++ that makes a unique_ptr to an object of type hd_private
          #[namespace = "biji"]
          fn new_private_key(seed: UniquePtr<ffi::libbitcoin::system::data_chunk>) -> UniquePtr<hd_private>;
      }
  }
  
  fn new_seed(bit_length: u8) -> UniquePtr<ffi::libbitcoin::system::data_chunk> {
      let fill_seed_size: u8 = bit_length / ffi::libbitcoin::byte_bits as u8;
      let mut seed = ffi::libbitcoin::system::to_chunk(fill_seed_size);
      let pin = seed.pin_mut();
  
      ffi::libbitcoin::system::pseudo_random_fill(pin);
      // Return the UniquePtr or the Pin?
      seed
  }
  
  
  fn main() {
  
      let seed = new_seed(192);
  }
```

**Comment by adetaylor** [comment]
Take a look at https://cxx.rs/extern-c++.html#reusing-existing-binding-types - it should be possible to use a type from the `ffi` mod within `bcffi`.

I added a test to ensure this works within https://github.com/google/autocxx/pull/566/files, along with documentation aroound this (and a bunch of other things). Please reopen this if it doesn't work for some reason.

**Comment by zkjanus** [comment]
thank you

**Comment by zkjanus** [comment]
@adetaylor this is an error I'm getting now while trying the above:
```
error[E0277]: the trait bound `CxxVector<u8>: ExternType` is not satisfied
   --> gen/libbitcoin/src/main.rs:37:9

        type data = crate::ffi::libbitcoin::system::data_chunk;
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ExternType` is not implemented for `CxxVector<u8>`
```
data_chunk is an alias to `std::vector<uint8_t>`in c++

Do I have to `impl` ExternType as it says here?
https://docs.rs/cxx/1.0.49/cxx/trait.ExternType.html#integrating-with-bindgen-generated-types

Thank you for the help again
