### ISSUE TITLE
C++ visibility modifiers aren't properly respected by autocxx

### ISSUE THREAD

**Issue by nside** [google/autocxx#573]
## Expected Behavior
Build without error

## Actual Behavior
```
error: calling a private constructor of class 'S2Polyline'
  cargo:warning=    return unique_ptr<_Tp>(new _Tp(_VSTD::forward<_Args>(__args)...));
  cargo:warning=                               ^
  cargo:warning=/Users/dlaprise/src/autocxx/examples/s2/target/debug/build/autocxx-s2-example-6e5e9bf9de75dcf9/out/autocxx-build-dir/cxx/gen1.cxx:40:101: note: in instantiation of function template specialization 'std::__1::make_unique<S2Polyline, S2Polyline &>' requested here
  cargo:warning=std::unique_ptr<S2Polyline> S2Polyline_make_unique1_autocxx_wrapper(S2Polyline& arg0) { return std::make_unique<S2Polyline>(arg0); }
  cargo:warning=                                                                                                    ^
  cargo:warning=s2geometry/src/s2/s2polyline.h:362:3: note: declared private here
  cargo:warning=  S2Polyline(const S2Polyline& src);
```

## Steps to Reproduce the Problem

1. Add `generate!("S2Polyline")` to examples/s2/src/main.rs (also include "s2/s2polyline.h")

**Comment by adetaylor** [comment]
Thanks for this report. Yes, at the moment we don't take account of C++ visibility modifiers and we should.

I think the first step here is https://github.com/rust-lang/rust-bindgen/issues/1926 or similar.

I'll hope to take another look at this in a couple of weeks, but probably not before then.

**Comment by adetaylor** [comment]
This now appears to be fixed. There's a test in `test_private_constructor_make_unique`. That was pre-existing prior to this issue, so I'm not sure how it ever passed. However, adding `generate!("S2Polyline")` now also works, and I think that's because some changes have landed here in the version of `autocxx-bindgen` pulled into 0.11.1.

**Comment by nside** [comment]
thank you!
