### ISSUE TITLE
Build with sanitizer fails

### ISSUE THREAD

**Issue by emakryo** [google/autocxx#574]
## Expected Behavior

The demo should be built and run with sanitizers.

## Actual Behavior

Failed to run the build script.

## Steps to Reproduce the Problem

Set environment variables, then build.

```
$ cd demo/
$ export RUSTFLAGS=-Zsanitizer=address
$ export CFLAGS=-fsanitize=address
$ export CXXFLAGS=-fsanitize=address
$ cargo +nightly build --target x86_64-unknown-linux-gnu
```

The last command fails with the following messages.
```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "/work/target/debug/build/autocxx-demo-0164a6db0342f178/build_script_build-0164a6db0342f178.10goavil986tivtz.rcgu.o"
~~~
Omit full build command
~~~

  = note: /usr/bin/ld: /work/target/debug/deps/libcxx-f6089ecafe1f834e.rlib(cxx.o): in function `__static_initialization_and_destruction_0(int, int)':
          /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/cxx-1.0.49/src/cxx.cc:665: undefined reference to `__asan_before_dynamic_init'
          /usr/bin/ld: /work/target/debug/deps/libcxx-f6089ecafe1f834e.rlib(cxx.o): in function `__static_initialization_and_destruction_0(int, int)':
          /usr/include/c++/8/iostream:74: undefined reference to `__asan_after_dynamic_init'
          /usr/bin/ld: /work/target/debug/deps/libcxx-f6089ecafe1f834e.rlib(cxx.o): in function `_GLOBAL__sub_D_00099_0_cxx.cc':
          cxx.cc:(.text._GLOBAL__sub_D_00099_0_cxx.cc+0x11): undefined reference to `__asan_unregister_globals'
          /usr/bin/ld: /work/target/debug/deps/libcxx-f6089ecafe1f834e.rlib(cxx.o): in function `_GLOBAL__sub_I_00099_1_cxx.cc':
          cxx.cc:(.text._GLOBAL__sub_I_00099_1_cxx.cc+0x5): undefined reference to `__asan_init'
          /usr/bin/ld: cxx.cc:(.text._GLOBAL__sub_I_00099_1_cxx.cc+0xa): undefined reference to `__asan_version_mismatch_check_v8'
          /usr/bin/ld: cxx.cc:(.text._GLOBAL__sub_I_00099_1_cxx.cc+0x1b): undefined reference to `__asan_register_globals'
          collect2: error: ld returned 1 exit status
```

It seems like some dependencies of build scripts are built with sanitizer.

## Specifications

- Version: 
  - rustc 1.55.0-nightly (a435b49e8 2021-06-28)
  - cargo 1.55.0-nightly (9233aa06c 2021-06-22)
- Platform:
  - Running on docker image (rust:latest)
  - Docker version 19.03.13-ce, build 4484c46
  - Ubuntu 18.04

**Comment by adetaylor** [comment]
Thanks for the report. We simply use the `cc` crate to build (https://docs.rs/cc/1.0.68/cc/), and we don't do anything weird, so I'm sure you'll find the same problem applies to any project you build using `cc`.

From the looks of the error, the linker needs to be educated about ASAN, so maybe you can add the same thing to `LDFLAGS`. That's a total guess though! To take this further I think you should make a minimal project case using `cc` and resolve it in that simpler context.

**Comment by emakryo** [comment]
This error happened in linking the build script, and build scripts should not use asan, right?
Just building cc examples with asan works fine.
