### ISSUE TITLE
Pin hell

### ISSUE THREAD

**Issue by WilliamVenner** [google/autocxx#579]
Hi there,

I just started using this library - I don't have much experience with C++ and am very confused about why my bindings are full of `Pin<T>` requirements. I couldn't find any documentation that offers any explanation into this or how to work effectively with it, and how to actually use the bindings without causing horrific UB.

I have a simple class and header which looks like this:

```cpp
class IEngine {
public:
	virtual int CreateSteamPipe(int*) = 0;
	virtual int BReleaseSteamPipe(int) = 0;
	virtual int CreateGlobalUser(int *) = 0;
	virtual int ConnectToGlobalUser(int) = 0;
	virtual int CreateLocalUser(int *, int) = 0;
...
```

As you can see, these are pure virtual functions. I receive a `void*` to an instance of an `IEngine` from an external dependency, and work with that, like this:

```rust
let engine = (STEAM_CLIENT.CreateInterface)(...) as *mut IEngine;
```

I expected to simply be able to call functions implemented on the IEngine class like so:

```rust
let engine = &mut *((STEAM_CLIENT.CreateInterface)(...) as *mut IEngine);
engine.CreateSteamPipe(...);
...
```

However, `CreateSteamPipe` does not exist for a mutable reference, it in fact exists for a `Pin<&mut IEngine>`, so I then tried:

```rust
let engine = std::pin::Pin::new(&mut *((STEAM_CLIENT.CreateInterface)(...) as *mut IEngine));
engine.CreateSteamPipe(...);
...
```

But this doesn't work:

![image](https://user-images.githubusercontent.com/14863743/128646908-ce82668c-c9de-4e8e-9423-64de3009808f.png)

I wanted to move forwards, so I opted to use `std::pin::Pin::new_unchecked` instead to shut the compiler up and continue, but I wouldn't be surprised if this was massive UB or something. I'm sure that bound is there for a reason?

Anyway, later I noticed that any function that requires this pinned mutable reference of course _moves_ the pin, meaning you have to construct a new pin every time you want to call a function. This doesn't sound right. I made this horrifying struct to "work around" it:

```rust
struct Pinner<'a, T>(&'a mut T);
impl<'a, T> Pinner<'a, T> {
	pub fn new(new: *mut T) -> Pinner<'a, T> {
		unsafe { Pinner(&mut *new) }
	}

	pub fn pin(&mut self) -> std::pin::Pin<&mut T> {
		unsafe { std::pin::Pin::new_unchecked(self.0) }
	}
}
```

Do you think you could clarify the idiomatic way to handle this, and why this is needed?

Is it within the scope of autocxx to create abstractions for handling this? Is this actually a cxx thing to enforce memory safety, and would the solution be to use a UniquePtr of some sort - how do I construct one?

Many thanks

**Comment by adetaylor** [comment]
Thanks for taking a look at autocxx.

> Do you think you could clarify the idiomatic way to handle this, and why this is needed?

Yes, I will. `cxx` added this requirement for non-const methods to be `Pin`ned relatively late in the evolution of autocxx, and I hadn't spotted this annoyance before either. I'm struggling with exactly the same situation as you, but I think I must be missing something about the normal way this is handled in plain old cxx, so I'm going to do a bit of research in how it does it.

**Comment by WilliamVenner** [comment]
Awesome thank you for your input :)

**Comment by adetaylor** [comment]
I think the ultimate solution here is probably https://github.com/dtolnay/cxx/issues/537 but I'm digging for more information in https://github.com/dtolnay/cxx/issues/910.

**Comment by adetaylor** [comment]
dtolnay@ explained the magical solution - use `Pin::as_mut` for each method call. I'm going to add an example to autocxx showing this pattern.

**Comment by WilliamVenner** [comment]
Ah ok. I wonder if we could implement `std::ops::Fn` somehow and implement `call` to do this automatically? Or just `DerefMut`, or `BorrowMut`?

**Comment by adetaylor** [comment]
Per [this comment](https://github.com/dtolnay/cxx/issues/910#issuecomment-896719894) it sounds like this is a limitation of the current `Pin` and may be fixed in future.
