### ISSUE TITLE
Should `autocxx::c_*` newtypes implement `Copy`?

### ISSUE THREAD

**Issue by WilliamVenner** [google/autocxx#580]
Hi,

I noticed that the wrapped C types autocxx exposes do not implement `Copy` - only `Clone`, despite most of them having `Copy` implemented on the underlying type - is this intentional?

https://github.com/google/autocxx/blob/4e96dfd9d885c44fbf8ae829aaa5f53dcff68d7f/src/lib.rs#L620-L633

Cheers

**Comment by adetaylor** [comment]
Thanks for the report. These `autocxx::c_*` types were intended to be a stop-gap measure until https://github.com/dtolnay/cxx/pull/874 lands, which in turn is blocked on https://github.com/dtolnay/cxx/issues/682. There's progress there in https://github.com/dtolnay/cxx/pull/908 thanks to @CAD97 so hopefully these nasty wrappers can go away soon.

However! Meanwhile yes they should probably implement `Copy`. I'll make that change.
