### ISSUE TITLE
demo fail to build

### ISSUE THREAD

**Issue by derust** [google/autocxx#6]
## Expected Behavior
build and run demo

## Actual Behavior

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.1c4ndla2a5ux5v3z.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.2h2pdaobccn6zeof.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.3g4mwhrnanfzo93l.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.3r8mkb28nvaav05s.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.4ap5xtkavab8p9x5.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.5f07d58ku19x5yd8.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.9ji2iqnqcygp0ue.rcgu.o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.jv3t67c94wp01u8.rcgu.o" "-o" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92" "/home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.4og2nil6wslwmztf.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/home/user1/autocxx-example/target/debug/deps" "-L" "/home/user1/autocxx-example/target/debug/build/autocxx-example-a1229e1cdb508885/out" "-L" "/home/user1/autocxx-example/target/debug/build/cxx-921c9432ffb813bf/out" "-L" "/home/user1/autocxx-example/target/debug/build/link-cplusplus-c635e2f5a57104e6/out" "-L" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lautocxx-example" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-lstdc++" "-Wl,-Bstatic" "/home/user1/autocxx-example/target/debug/deps/libcxx-2d7be6e04495aa40.rlib" "/home/user1/autocxx-example/target/debug/deps/liblink_cplusplus-6f18b49319e43bc3.rlib" "-Wl,--start-group" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-cf0f33af3a901778.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-daf8c2d692e6eca4.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-24e8f97647425e48.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-85ed7d2b484c05a9.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-89de2c581262ec09.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-3b0db98e62ed7d75.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-c60847f9a163de82.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-0bb9b63424f4fc5d.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-3f74d829e37fa40e.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-0e9d83ff06f1a7ad.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-2c8c904efaf7c40b.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-cbfb51de52131460.rlib" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-97497c26fddb7882.rlib" "-Wl,--end-group" "/home/user1/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-f1a9d8c443e20b5e.rlib" "-Wl,-Bdynamic" "-lstdc++" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /home/user1/autocxx-example/target/debug/deps/autocxx_example-ad7f19bfc3950f92.jv3t67c94wp01u8.rcgu.o: In function `autocxx_example::ffi::cxxbridge::DoMath':
          /home/user1/autocxx-example/src/main.rs:3: undefined reference to `cxxbridge04$DoMath'
          collect2: error: ld returned 1 exit status

## Steps to Reproduce the Problem

1. cargo build

## Specifications

- Version:
autocxx v0.2.0

- Platform:
 Ubuntu 18.04 LTS

**Comment by adetaylor** [comment]
Thanks for the report.

How did you fetch the `demo` code?

If you got it from git, then I think you'd have needed to also fetch the cxx code from git, and I think it would have worked. It looks to me like you must have downloaded an archive of the autocxx code which ended up using mismatched versions of `cxx` and `cxx::gen`.

This is probably the first step to fixing that: https://github.com/dtolnay/cxx/pull/306 then I'll need to republish autocxx to depend upon the more recent version.

**Comment by adetaylor** [comment]
I published 0.3 which I hope will fix this. Please reopen if not!
