### ISSUE TITLE
`inline` functions defined in C++ header can't be found.

### ISSUE THREAD

**Issue by SilensAngelusNex** [google/autocxx#60]
Defining a function in a header file with `inline` causes the following error:

```
error[E0425]: cannot find function `calculate` in module `ffi::cxxbridge`
 --> $DIR/input.rs:1:137
  |
1 | ... fn main () { assert_eq ! (ffi :: cxxbridge :: calculate () , 42) ; } # [link (name = "autocxx-demo")] extern { }
  |                                                   ^^^^^^^^^ not found in `ffi::cxxbridge`
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
```

Removing `inline` from the declaration and moving the definition of the function the cxx file fixes the error, but some C++ libraries define functions in the header using inline as an optimization, so I would expect `autocxx` to be able to find them.

```rust
// integration.rs
let hdr = indoc! {"
    #include <cstdint>
    inline uint32_t calculate() { return 42; }
"};
let cxx = indoc! {"
"};
let rs = quote! {
    assert_eq!(ffi::cxxbridge::calculate(), 42);
};
run_test_with_full_pipeline(cxx, hdr, rs, &[
    "calculate",
], &[]);
```

**Comment by adetaylor** [comment]
Thanks for the report! This can probably be fixed by doing [the steps described here](https://rust-lang.github.io/rust-bindgen/faq.html#why-isnt-bindgen-generating-bindings-to-inline-functions) in the instructions we pass to bindgen.

**Comment by adetaylor** [comment]
If you think you might be about to have a crack at this, you should add the relevant bindgen directives to the `make_bindgen_builder` function: https://github.com/google/autocxx/blob/main/engine/src/lib.rs#L212 and see what blows up!

**Comment by adetaylor** [comment]
On the "what blows up" front, I suspect bindgen will probably try to translate larger parts of the STL and will therefore fail. It may be necessary to add more to thee `BINDGEN_BLOCKLIST` list, but after that I expect this will all work.

(In terms of the warnings about performance of hot functions, that's why #52 is important).
