### ISSUE TITLE
Failing tests against cxx 0.5.3

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#64]
https://github.com/google/autocxx/runs/1354644122?check_suite_focus=true

Probably because of cxx 0.5.3 changes? Will investigate later today.

**Comment by dtolnay** [comment]
Probably just needs a bump to cxx-gen 0.6.0. The generated C++/Rust code use internal APIs to communicate between one another so running a new Rust code generator with an old C++ code generator is equivalent to relying on non-semver-covered private APIs. (This is also why I was somewhat hesitant to settle on a cxx-gen versioning scheme.)

**Comment by adetaylor** [comment]
Yep. When I escape from meetings I will give that a try :)
