### ISSUE TITLE
autocxx-engine fails to build on its own

### ISSUE THREAD

**Issue by CAD97** [google/autocxx#645]
## Steps to Reproduce the Problem

The crate deliberately does not enable `syn/extra-traits` to skip implementing `Debug` for syn types. Unfortunately, it still relies on syn types implementing `Debug` for at least:

- `TypeConversionPolicy` derives `Debug` and contains `syn::Type`
- `SuperclassMethod` derives `Debug` and contains a lot of `syn` types

Removing those types' `Debug` derives allows the crate to compile.

## Specifications

- Version: autocxx-engine-0.12.0

**Comment by CAD97** [comment]
https://github.com/google/autocxx/blob/a9ee99fefdab5a86589a88e926adb8d60d5bb97f/engine/src/conversion/codegen_rs/mod.rs#L124-L131

https://github.com/google/autocxx/blob/6c10e89de12ac9ac308b67dcf88ccca373ccc058/engine/src/conversion/analysis/fun/function_wrapper.rs#L56-L61

**Comment by CAD97** [comment]
All I did was make a project using `autocxx` and `autocxx_build` at build time.

syn's extra-trailts feature is being enabled transitively in this workspace by `strum_macros`... so the issue is that I'm using `resolver=2`, I believe.

**Comment by CAD97** [comment]
(In order to check what enabled the feature, I used `cargo tree -e features -i syn`, which is a very useful tool to have in your toolbox.)

**Comment by adetaylor** [comment]
Fixed by #646, thanks for the report. I hope to make a new release sometime in the next couple of days.
