### ISSUE TITLE
``int`` in Pod?

### ISSUE THREAD

**Issue by Vurv78** [google/autocxx#667]
Hello!
I am trying to generate struct bindings to a library that uses types like ``int`` which seem to be un 'pod' able (versus types like uint32_t). Is there a solid way to deal with this? 😕

Also: Maybe adding an example with generate_pod would be useful as I only see it in the unit tests https://github.com/google/autocxx/blob/ff2b0ee07887c3a5a9bbfbb3e2b731a7a07d7028/integration-tests/src/tests.rs#L6720-L6726

## Expected Behavior
Be able to send types like ``int`` through struct/pod ffi

## Actual Behavior
``Unable to parse include_cpp! macro: autocxx could not generate the requested bindings. An item was requested using 'generate_pod' which was not safe to hold by value in Rust. Type bruh could not be POD because its dependent type std::os::raw::c_int isn't known``

## Steps to Reproduce the Problem
1.
```c
struct thestruct {
	int inner;
};
```
2.
```rs
include_cpp! {
	...
	generate_pod!("thestruct")
}
```

## Specifications

- Version: 0.13.0
- Platform: Windows 64 Bit

**Comment by adetaylor** [comment]
Thanks for the nice clear report - I added an (intentionally failing) test here:
https://github.com/google/autocxx/pull/669

I'll see if it's an easy fix!

**Comment by adetaylor** [comment]
OK, I pushed a possible fix, but it wouldn't surprise me if it causes some other failures on other tests - I'll wait and see.

I will also, as you suggest, add an example here. POD data hasn't been high on my list of priorities, especially since I hope in future #379 allows us to drop the whole distinction between POD and non-POD.

**Comment by Vurv78** [comment]
Thank you for such a quick response!
Tested it out with a local submodule, doesn't seem to work and still gives the same error :/

Also excited for #379, hopefully it isn't too far away 👍

**Comment by adetaylor** [comment]
> doesn't seem to work and still gives the same error :/

Could you have a look at the integration test I added in this pull request and let me know what's different in your test case?

Better still, if there is a difference, please raise a PR which adds a (failing) integration test.

**Comment by Vurv78** [comment]
I think the CI was also failing on the new test you added for the same reason, can't check right now as github mobile is limited :p

**Comment by adetaylor** [comment]
CI is happy now. I first pushed the failing test, intentionally, then a fix, which made it go green. No hurry to check!

**Comment by Vurv78** [comment]
Ah, looks like it was just an issue with me including autocxx-build as version 0.12.0 instead of also using it as a gitmodule

This fixes the issue, thank you!
The only strife I have now is that having this as a git dependency seems to fail, but I will just use it as a submodule for now / wait for the cargo release!
