### ISSUE TITLE
How to dynamically provide location of `.h` files at build time? (Example usage: different headers in different platforms)

### ISSUE THREAD

**Issue by fzyzcjy** [google/autocxx#675]
Hi thanks for the lib! I wonder how to dynamically provide location of `.h` files at build time? I have different headers in different platforms, so I cannot hardcode a `somefile.h` in my `include_cpp!` macro.

**Comment by adetaylor** [comment]
Hi, if you're talking about different _directories_ of header files, you can provide them in your `build.rs` - for example by querying on [these environment variables](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-build-scripts).

If you're talking about different header _files_ within the same directory, that's trickier. Here are two solutions.

1. Create your own `.h` file which `#include`s the others, selectively based on `#ifdef`. I think in your `build.rs` you can then use `Builder.extra_clang_args` to pass `-Dsome-platform`. I just realized `Builder` isn't documented - #677.
2. You could have multiple copies of your entire `include_cpp!` macro invocation, chosen based on `cfg!` or similar.

**Comment by fzyzcjy** [comment]
Thank you!
