### ISSUE TITLE
Ignore protected member functions

### ISSUE THREAD

**Issue by fzyzcjy** [google/autocxx#676]
## Expected Behavior
no error

## Actual Behavior
has error

## Steps to Reproduce the Problem

```
class Hello {
public:
    Hello();
    int public_function();
protected:
    int protected_function();
};
```

with

```
include_cpp! {
    #include "input.h"
    generate!("Hello")
}
```

yields

```
 running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "src" "-I" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/include" "-Wall" "-Wextra" "-DMY_BUILD_TARGET_MACOS=1" "-std=c++14" "-o" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/cxx/gen0.o" "-c" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/cxx/gen0.cxx"
  cargo:warning=/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/cxx/gen0.cxx:149:57: error: 'protected_function' is a protected member of 'Hello'
  cargo:warning=  ::c_int (::Hello::*protected_function$)() = &::Hello::protected_function;
  cargo:warning=                                                        ^
  cargo:warning=src/input.h:30:9: note: declared protected here
  cargo:warning=    int protected_function();
  cargo:warning=        ^
  cargo:warning=1 error generated.
  exit status: 1

  --- stderr
  Start ncnn_rust build script target=Macos


  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "src" "-I" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/include" "-Wall" "-Wextra" "-DMY_BUILD_TARGET_MACOS=1" "-std=c++14" "-o" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/cxx/gen0.o" "-c" "/Users/tom/QAPMain/Development/frontend/ncnn_rust/target/debug/build/ncnn_rust-2cef91cead1f1e2d/out/autocxx-build-dir/cxx/gen0.cxx" with args "c++" did not execute successfully (status code exit status: 1).
```

Thus, is there, at least, some workarounds? I have tried `block!` on `Hello::protected_function` but completely no use. This make autocxx not useable...

## Specifications

- Version: latest
- Platform: macos

**Comment by adetaylor** [comment]
Thanks for the report. Whilst this is a known limitation of autocxx, I do agree that this has now bubbled up the priority list enough that we should fix it.

("Fix it" = ignore these functions, whilst generating all the rest properly).

I'll try to take a look at this sometime in the next couple of weeks. If you want to expedite matters, please raise a pull request which adds a suitable (failing) test cases to `integration-tests/src/tests.rs`. That makes it as easy as possible for me to just focus on adding a fix. If you decide to do this, it would be great if you can add test cases for both protect and private methods.

**Comment by fzyzcjy** [comment]
@adetaylor Thank you! So I wonder what should I do now? I definitely need to use autocxx on these (thirdparty) classes!

**Comment by fzyzcjy** [comment]
PR: https://github.com/google/autocxx/pull/678

**Comment by fzyzcjy** [comment]
@adetaylor This is blocking my app development... Could you please give some hints and I can try to make a fix (if not too hard)

**Comment by fzyzcjy** [comment]
@adetaylor Ah you already fixed it? So quick! Thank you!

**Comment by adetaylor** [comment]
Thanks for adding the tests, that made it very easy for me to implement a fix.

I'm unlikely to get around to releasing a new version of autocxx in the next few days, but there is a way to specify in your `Cargo.toml` that you want to use the version from git. (Obviously, we need to wait and see if this fix breaks any of the other tests before I merge it into main)

**Comment by fzyzcjy** [comment]
> use the version from git

Sure I will use the github version. Thanks for the quick fix!
