### ISSUE TITLE
Possible dependency graph pollution

### ISSUE THREAD

**Issue by themaxdavitt** [google/autocxx#708]
[`autocxx-engine` appears to be using the default features of `autocxx-bindgen`](https://github.com/google/autocxx/blob/v0.14.0/engine/Cargo.toml#L37), which is [including CLI-related packages](https://github.com/adetaylor/rust-bindgen/blob/0ea6e78736dce5c4e9f1ef71e272ec8373fe0803/Cargo.toml#L72) in the dependency graph. It also [has the `reproduction_case` feature enabled by default](https://github.com/google/autocxx/blob/v0.14.0/engine/Cargo.toml#L27), which I believe should instead be [enabled in `tools/reduce`, like with `autocxx-parser`](https://github.com/google/autocxx/blob/v0.14.0/tools/reduce/Cargo.toml#L10-L11), so we're not introducing `serde_json` and friends unnecessarily. My apologies if I misidentified these, I am relatively new to this project.

**Comment by adetaylor** [comment]
Thanks.

I'd certainly accept a pull request to `autocxx-engine` to prune the dependencies around `autocxx-bindgen` features.

The `reproduction_case` feature is intentionally enabled by default, though. I want people to be able to report bugs as easily as possible, even though it pulls in lots of stuff.
