### ISSUE TITLE
Ignore protected inner classes/structs

### ISSUE THREAD

**Issue by laptou** [google/autocxx#709]
I'm having an issue where I'm trying to bind to a header which contains a class which contains a protected structure: the bindings reference the protected structure, which is causing issues.

**Comment by laptou** [comment]
This seems pretty similar to #676, so I'm trying to follow your example in #679 and develop a PR

**Comment by laptou** [comment]
I'm not sure how to make this error appear in the integration tests, because it doesn't actually fail until the part where you try to compile the generated code with `cc`, which means the tests will have to include that part.

**Comment by adetaylor** [comment]
> I'm not sure how to make this error appear in the integration tests, because it doesn't actually fail until the part where you try to compile the generated code with cc, which means the tests will have to include that part.

That should be OK. Each integration test should go ahead and build and run the C++ you provide in it.

Thanks a ton for working to make a test, it's much appreciated.

**Comment by laptou** [comment]
After looking at this for a while, I have no idea how to fix this. But please let me know if I can help!

**Comment by adetaylor** [comment]
Work in progress here: https://github.com/adetaylor/rust-bindgen/pull/new/comp-visibility

We need to:
* Emit attributes from autocxx-bindgen if an inner type is protected (the branch above does that, but in a silly way, so I need to redo it)
* Detect those attributes in autocxx and ignore types thus annotated.

I'm unlikely to finish this for the next few weeks, unfortunately.

But thanks for the report and the minimal test case, that enabled me to track down the problem very fast so I should be able to fix this pretty fast when I get proper time on it. Cheers!

**Comment by benesch** [comment]
Just ran into this myself! Going to see if I can pick this up. 🤞🏽 

To start, I _think_ I have a cleanup of your comp-visibility change to bindgen that I've tossed up here: https://github.com/adetaylor/rust-bindgen/pull/7

I'm looking at what changes are required in autocxx now.

**Comment by benesch** [comment]
I put together a sort of hacky set of autocxx changes to fix this in #711.
