### ISSUE TITLE
Ignore rvalue references

### ISSUE THREAD

**Issue by benesch** [google/autocxx#712]
It'd be swell if autocxx could just ignore functions that involve rvalue references. Here's a test that will fail because bindgen/autocxx currently isn't aware that an rvalue ref can't be codegen'd like an lvalue ref:

```diff
diff --git a/integration-tests/src/tests.rs b/integration-tests/src/tests.rs
index 2bd25b6..abba7ce 100644
--- a/integration-tests/src/tests.rs
+++ b/integration-tests/src/tests.rs
@@ -5297,6 +5297,17 @@ fn test_ignore_move_constructor() {
     run_test("", hdr, rs, &["A"], &[]);
 }
 
+#[test]
+fn test_ignore_function_with_rvalue_ref() {
+    let hdr = indoc! {"
+        #include <string>
+
+        void moveme(std::string &&);
+    "};
+    let rs = quote! {};
+    run_test("", hdr, rs, &["moveme"], &[]);
+}
+
 #[test]
 fn test_overloaded_ignored_function() {
     // When overloaded functions are ignored during import, the placeholder
```

Note that for my use case I have a stack of overloads, one of which takes a string by rvalue reference. I'd be perfectly happy to just drop that one overload on the floor. It sounds like #379 might some day support _actual_ move C++ semantics, which would be awesome, but not something I personally need yet!

**Comment by adetaylor** [comment]
Yeah. I am just _beginning_ to make the very earliest beginnings of progress on #379, but I anticipate it being a multi-month effort.

I would be happy to accept a PR which ignores these things meanwhile.

Meanwhile a PR which adds the above test with an `#[ignore]` annotation would be helpful.

**Comment by benesch** [comment]
> Yeah. I am just _beginning_ to make the very earliest beginnings of progress on #379, but I anticipate it being a multi-month effort.

👍🏽 makes sense

> I would be happy to accept a PR which ignores these things meanwhile.

Awesome! I might try to put that together if I find the time. It might actually be a helpful step _towards_ #379, since bindgen needs to be taught to distinguish between rvalue and lvalue refs no matter what. 

> Meanwhile a PR which adds the above test with an `#[ignore]` annotation would be helpful.

Done in #715!
