### ISSUE TITLE
Experiment with generating all

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#75]
At the moment, it's mandatory to provide one or more `allow` directives. They builds the allowlist which we feed to bindgen. However, if no allowlist is fed to bindgen it attempts to generate bindings for everything which it encounters in the header files.

It might be worth adding an `allow_all` directive which bypasses the creation of the `NoAllowlist` error but has no other effect: this should be sufficient to ask bindgen to generate bindings for everything.

In practice, with realistically complex headers (i.e. using STL), I expect problems correctly interpreting some of the items in the headers. But that's probably a good reason to try.

**Comment by adetaylor** [comment]
`allow` has since been renamed to `generate` so this would become `generate_all`

**Comment by martinboehme** [comment]
I think there could be a worthwhile middle ground here: Generate bindings not for everything, but for all definitions contained directly in the headers mentioned in the `include_cpp!` (i.e. not in transitively included files) and for all types used in those definitions.

This would be in the spirit of "include what you use". It would also avoid producing the really large amounts of output that a true "generate all" might produce on a header that pulls in a lot of definitions through transitive includes. It would, however, require some modifications to bindgen, I think.

BTW, should the title of this bug be renamed to "Experiment with `generate_all`"?

**Comment by adetaylor** [comment]
Thanks for the suggestion. I hadn't thought of it, but I'd be a bit concerned that some projects might expose a "logical" header to their clients which actually just `#include`s a further set of headers for their implementation. C++ projects might feel free to move things around internally between header files, so this could cause breakage when people upgrade to new versions of those projects. WDYT?

**Comment by martinboehme** [comment]
Hm, that's true.

Essentially, this would require something akin to `pub use` on the C++ side to mark a header as "re-exported". The "include what you use" tool defines the [`export` pragma](https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/IWYUPragmas.md#iwyu-pragma-export) for this, but this is obviously specific that particular tool, so it wouldn't be suitable for our purposes.

Probably, the only good solution to this is to use C++ modules, which make all of this explicit, but this doesn't seem worth doing before C++ modules come into widespread use.

It might still be worth offering this a "generate all from header" option for use in projects that have a convention that only declarations from a header itself should be used.

**Comment by adetaylor** [comment]
OK, I had a crack at this today in #438.

Conclusions:
* We need to think on the syntax for this. It would be nice to generate everything by default in the absence of any `generate!` directives so that people can just do:
```rust
autocxx::include_cpp! {
  #include "foo.h"
}
```
... but that conflicts with the current POD declaration style.
* It works for the simple demo example.
* It seems to nearly work for the s2 example, except for #442 and #443.
* It doesn't come close to working for Chrome, because it seems like `bindgen` gets stuck an an infinite loop. I have yet to characterize this.
