### ISSUE TITLE
rvalue parameters will make overloads ignored

### ISSUE THREAD

**Issue by steeve** [google/autocxx#768]
## Expected Behavior

Given these two methods:
```cpp
torrent_handle add_torrent(add_torrent_params&& params);
torrent_handle add_torrent(add_torrent_params const& params);
```

Only the first should be ignored.

## Actual Behavior

While the first method is properly ignored, the second is too:
```rust
fn add_torrent(_uhoh: autocxx::BindingGenerationFailure) {}
#[doc = "autocxx bindings couldn't be generated: This function takes an rvalue reference parameter (&&) which is not yet supported."]
fn add_torrent2(_uhoh: autocxx::BindingGenerationFailure) {}
#[doc = "autocxx bindings couldn't be generated: This function takes an rvalue reference parameter (&&) which is not yet supported."]
```

If I comment out the first one (with the rvalue param), then the second one is properly generated.

## Specifications

- Version: `master` as of 2022-01-30
- Platform: macos

Great job so far!

**Comment by adetaylor** [comment]
Thanks for the report! Would you be kind enough to open a pull request to add a failing test to `integration-tests/src/tests.rs`? That will enable me to fix it much more quickly.

**Comment by steeve** [comment]
Nevermind, working on the test, it seems `add_torrent1` was generated properly.
I got confused because `add_torrent` and `add_torrent2` where right next to each other and it didn't occur to me there would be a `1` suffixed version.
Very sorry for the noise.
