### ISSUE TITLE
`--generate-exact` doesn't produce predictable header filenames

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#773]
## Expected Behavior

According to the `gen --help`, using `--generate-exact` is supposed to produce easily predictable output filenames. This would be helpful for #478.

## Actual Behavior

The `.cc` files have predictable names, but the `.h` ones don't. They depend on the `include_cpp!` module names. This means my Bazel rule has to know all of the module names ahead of time to predict the `.h` filenames, which is a minor annoyance.

Having an option to name the `.h` files the same as their corresponding `.cc` files would be nice.

## Specifications

- Version: 0.16.0

**Comment by adetaylor** [comment]
Hm, sorry about that. I'd be happy to accept a PR to fix it! `--generate-exact` is kind of annoying to have to maintain, but it exists exactly for things like bazel that require predictable names, so I'd be completely open to whatever fix is needed.

**Comment by bsilver8192** [comment]
I'm working on this now.
