### ISSUE TITLE
No `safety!` results in `unsafe fn drop`, which doesn't compile

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#788]
## Expected Behavior
Always generate safe `drop` implementations, as required by `Drop`.

## Actual Behavior
With `safety!(unsafe)` or `safety!(unsafe_ffi)`, it's fine. Without any `safety!`, `drop` ends up being marked `unsafe`, which doesn't compile.

## Steps to Reproduce the Problem
See #789 for a failing test.

## Specifications

- Version: 49665846d6219d149fe11f9a39e9e4fa5001ac26
- Platform: Linux

**Comment by adetaylor** [comment]
I really appreciate the addition of the test, thanks! I'm hoping this one is an easy fix, we'll see.

**Comment by bsilver8192** [comment]
Thanks!
