### ISSUE TITLE
Run test suite & examples on more platforms in CI

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#796]
Right now our github actions test things on Linux only. The `cxx` crate has actions to test things on all sorts of platforms. We should too.

**Comment by philipcraig** [comment]
I will take this

**Comment by philipcraig** [comment]
@adetaylor As `creduce` isn't available on Windows or MacOS, I will have to exclude any tests that need it. Would you still like to have CI build on those platforms and run the limited tests that don't need `creduce`, or what would you like to do?

**Comment by adetaylor** [comment]
Thanks for checking. Yes, the most important things are the examples and the tests in `integration-tests` neither of which need `creduce`. Thanks for working on this!

**Comment by philipcraig** [comment]
The `chromium-fake-render-frame-host` example fails to link on Windows (using Visual Studio 2022) with error:

```
autocxx-fake-render-frame-host-example.lib(gen0.o) : error LNK2019: unresolved external symbol
"public: static class content::WebContents * __cdecl content::WebContents::FromFrameTreeNodeId(int)"
(?FromFrameTreeNodeId@WebContents@content@@SAPEAV12@H@Z)
referenced in function
"class content::WebContents * __cdecl FromFrameTreeNodeId_autocxx_wrapper(int)"
(?FromFrameTreeNodeId_autocxx_wrapper@@YAPEAVWebContents@content@@H@Z)
```

**Comment by philipcraig** [comment]
The following integration tests fail on Windows:

```
failures:
    tests::test_bitset
    tests::test_forward_declaration
    tests::test_nested_type
    tests::test_private_inner_class
    tests::test_protected_inner_class
    tests::test_stringview
    tests::test_typedef_to_ulong
```
