### ISSUE TITLE
LLVM requirement link in README points to print page

### ISSUE THREAD

**Issue by est31** [google/autocxx#8]
If you follow this link in README:

> It requires llvm to be installed due to bindgen

It'll lead to a print page (print.html in the url). I think the print.html component should be removed.

I would have filed a PR but I'm not signing any CLA unless Google pays me money.

**Comment by adetaylor** [comment]
Thank you! I will fix it over the next couple of days. CLA concerns noted and can be frustrating on all sides :(

**Comment by est31** [comment]
Thanks for making autocxx and thanks for the fix. You folks rock!
