### ISSUE TITLE
rustfmt CI action is a bit broken

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#805]
The `rustfmt` github action relies on pushing a commit with the formatted code. This never works. Either:

* The code is in someone else's fork, and it doesn't have permission to fix it. Or,
* The code is in the main autocxx repo, and the CLA bot gets Very Angry that some other bot would _dare_ commit some code.

I asked internally about this second situation, and apparently it's unsolvable. Therefore we should modify the `rustfmt` action so it's just pass/fail instead of trying to add a commit.

**Comment by adetaylor** [comment]
(That said, the `rustfmt` bot is _useful_ in that it enforces we can't land anything with bad formatting. It's just that its diagnostics make no sense)

**Comment by philipcraig** [comment]
I am working on a rust format bot change as part of #796

**Comment by philipcraig** [comment]
Am addressing as part of PR for #796

**Comment by RishiKumarRay** [comment]
@adetaylor  what if we specify this only to check formatting ? Let me know
steps:
    - uses: actions/checkout@v2
    - name: Check formatting
      run: cargo fmt -- --check
