### ISSUE TITLE
Explicitly defaulted default/copy/move constructors are treated as present

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#815]
## Expected Behavior
They should be handled the same as implicitly defaulted constructors (aka no user-defined ones). This means they may be deleted or present, depending on the members and bases.

## Actual Behavior
autocxx always tries to call them, even if they're actually deleted.

I'm fixing lots of other kinds of trickiness with implicitly defaulted constructors right now, but I think this one requires extra bindgen annotations so I'm going to leave it for now.

**Comment by adetaylor** [comment]
Ah, it was kind of amazing that nobody spotted bugs in that constructor-related logic until now. Good spot.

**Comment by bsilver8192** [comment]
Note that Clang has a default-enabled [-Wdefaulted-function-deleted](https://clang.llvm.org/docs/DiagnosticsReference.html#wdefaulted-function-deleted) which warns about C++ code triggering this. I think that replacing `= default` with `= delete` has the exact same behavior in C++ while avoiding this limitation.

**Comment by youben11** [comment]
I tried to follow referenced PRs/issues to know whether the bug is actually fixed or not, but I couldn't be certain. So I'm using the latest version (0.22.4) and I observe a similar behavior, as autocxx generates code that tried to call some copy constructors that were implicitly deleted.

**Comment by adetaylor** [comment]
@youben11 I don't think this is believed to be fixed yet.

**Comment by youben11** [comment]
thanks @adetaylor. So the current workaround would be to explicitly mark them deleted in Cpp, but is there a workaround in rust (autocxx) if I can't touch the Cpp code?

**Comment by adetaylor** [comment]
I think all you can do is explicitly `block!(mlir::DiagnosticEngine::DiagnosticEngine)` but I appreciate this may make autocxx useless for your needs.

**Comment by youben11** [comment]
I didn't knew there was a way to do it! This is actually awesome! I don't need this specific type (`mlir::DiagnosticEngine`), so I can definitely block it as far as it doesn't affect my other generated types, which is the case as far as I understand.

**Comment by adetaylor** [comment]
Some work in progress:
* #1180
* https://github.com/adetaylor/rust-bindgen/compare/master...adetaylor:rust-bindgen:denote-defaulted

These two PRs don't yet connect together: although autocxx now knows about defaulted functions, it doesn't treat them any differently than it does now. Also, the test case is very much incomplete.

**Comment by adetaylor** [comment]
I think this was fixed in #1180.
