### ISSUE TITLE
Decide what to do about failing tests on beta channel

### ISSUE THREAD

**Issue by philipcraig** [google/autocxx#818]
#817 shows that integration tests fail intermittently on the `rustup` beta channel.

Seems like it's very likely related to https://github.com/rust-lang/rust/issues/92595

If they backport the fix as they are discussing, this will go away.

If they don't and promote to stable, `autocxx` will be thoroughly unreliable. Or maybe just its tests?

Mentioned the bug here as they seem to be keen to promote the bug to stable "as-is" https://github.com/rust-lang/rust/issues/94124#issuecomment-1047655362

**Comment by philipcraig** [comment]
> Is your CI system actually reusing previous build states, or otherwise deliberating exercising incremental compilation? (If it is, that's very interesting, and I'm happy to hear it.)

It's my understanding that the CI is deliberately exercising incremental compilation. I cannot make one of the failing tests fail on its own, though it often fails when build just two tests. It is using the `trybuild` crate a few hundred times to compile a few hundred Rust integration tests, each in its own compilation unit. However, each test doesn't start with an empty directory, so, incremental.

**Comment by pnkfelix** [comment]
okay. we're disabling incremental compilation's default settings in 1.59, as described here: https://github.com/rust-lang/rust/pull/94224/commits/6af5faf7928c989e5b8bb6b006bec293e4376656

**Comment by philipcraig** [comment]
> okay. we're disabling incremental compilation's default settings in 1.59.0, as described here: [rust-lang/rust@6af5faf](https://github.com/rust-lang/rust/commit/6af5faf7928c989e5b8bb6b006bec293e4376656)

@pnkfelix Thanks for this information. When should that hit the beta rust channel?

**Comment by pnkfelix** [comment]
@philipcraig The compiler team has not decided to disable incremental compilation in the beta channel; that change is restricted to the stable channel alone, for now.

The problems that you're seeing in the current beta are *believed to be* fixed in the nightly channel. The nightly-to-beta promotion is underway as we speak, in https://github.com/rust-lang/rust/pull/94228; after that lands, then a new beta that we believe will address your problem should be available sometime soon thereafter (within a day at most I expect, but in this case the release team might launch the build sooner than the cron job would automatically trigger).

**Comment by philipcraig** [comment]
> The problems that you're seeing in the current beta are _believed to be_ fixed in the nightly channel. The nightly-to-beta promotion is underway as we speak, in [rust-lang/rust#94228](https://github.com/rust-lang/rust/pull/94228); after that lands, then the new beta should be available sometime soon thereafter (within a day at most I expect, but in this case [the release team might launch the build sooner](https://zulip-archive.rust-lang.org/stream/241545-t-release/topic/release.20process.html#272818294) than the cron job would automatically trigger), and we believe that new beta will also address your problem.

@pnkfelix Thanks for the update. I can confirm that the CI here currently does not see these issues on nightly.
