### ISSUE TITLE
Sort out `flag_if_supported` / hard-coded C++ language level flags

### ISSUE THREAD

**Issue by philipcraig** [google/autocxx#824]
Should [this](https://github.com/google/autocxx/blob/a7c8b65b5d65ea12f587c5a844a4ace150de5fee/integration-tests/tests/test_utils.rs#L387]) be `flag_if_supported`? It seems surprising this works! Obviously, it does though...

_Originally posted by @adetaylor in https://github.com/google/autocxx/pull/817#discussion_r811534814_

Relates to #819

**Comment by philipcraig** [comment]
I tried changing `flag` to `flag_if_supported` during development of #817. It broke`test_stringview` on ubuntu in such a way that it showed that the customisation in that test that overrides flags (in a hardcoded way for `gcc`/`clang` compilers for C++17 is broken.

My initial hypothesis (without following any code paths) is that when the integration test compiler command lines are constructed, first `flags` are applied, then any hard-coded extra flags are applied (`test_stringview` passes a hardcoded `gcc`/`clang` "-std=c++17" flag as a string, then finally any `flag_if_supported`s are applied. This changes the final result back to C++14 and hence `test_stringview` fails.

This issue is to say that the flags need sorting out in a compiler-independent way, if non `gcc`/`clang` compilers are to be supported in the integration tests. Hard-coded test-specific language standard-specifying strings have to go in favour of a symbolic language setting parameter that finally builds up to a correct set of flags when the compile command is constructed (possibly via `flag_is_supported` at that step.

I'll take a look.

**Comment by adetaylor** [comment]
Thanks; however, I consider all of this to be well into the domain of `cc` rather than `autocxx` so the investigation you've done already is more than sufficient to put my mind at rest that we're doing a half-way reasonable thing here.

**Comment by philipcraig** [comment]
I've traced flow of control now and the hypothesis was mostly correct but not quite.

The issue is that the `ClangArgAdder` uses any extra argument strings passed in for two purposes:
1. https://github.com/google/autocxx/blob/4077861fa3f9adca1518f0dee0efddf29f8d584b/integration-tests/tests/test_utils.rs#L432
2. https://github.com/google/autocxx/blob/4077861fa3f9adca1518f0dee0efddf29f8d584b/integration-tests/tests/test_utils.rs#L437

The use at 2. is mostly fine -- we can change `flag` to `flag_is_supported` and all is well. Anything set there is only sent to a compiler if it supports it.

The use 1. is the issue -- this is sent directly to `clang`, no questions asked at https://github.com/google/autocxx/blob/4077861fa3f9adca1518f0dee0efddf29f8d584b/engine/src/lib.rs#L291

I propose to change `run_test_ex` down through to `builder` to keep two separate parameter collections in `BuilderModifier` where now there is just one. One set would be passed to `bindgen` as `clang_args` and the other set is for the compiler being used in the tests. 

https://github.com/google/autocxx/blob/4077861fa3f9adca1518f0dee0efddf29f8d584b/integration-tests/tests/test_utils.rs#L349 would read one set of the `BuilderModifier` parameters and

https://github.com/google/autocxx/blob/4077861fa3f9adca1518f0dee0efddf29f8d584b/integration-tests/tests/test_utils.rs#L435 would read the other set.

All the above ceremony would let us pass clang flags to `clang`, and msvc flags to `msvc`.

@adetaylor what do you think about this?
