### ISSUE TITLE
Upgrade clap

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#831]
Two projects in the workspace depend on `clap` `2.x`. We should upgrade to `3.x`.

**Comment by gabriel-viviani** [comment]
Hey @adetaylor I'm a 5y software developer learning rust. Can I pick this one?! I'd take a bit of time to understand project ecosystem to proper test lib migration, but I sure wanna take that!

**Comment by adetaylor** [comment]
That would be awesome! Thanks! And yeah, there's no hurry.

**Comment by adetaylor** [comment]
Fixed by @gabriel-viviani in #834 and #1037. Thanks!
