### ISSUE TITLE
No compiler error for `generate_pod!` on a type with nontrivial move constructor or destructor

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#835]
## Expected Behavior
It's documented that this will fail.

## Actual Behavior
Various bad things at runtime. For example, destructors get run twice: once for the field's type and then again by the containing type's destructor. More levels of nesting will call them even more.

**Comment by bsilver8192** [comment]
My big "follow the C++ rules for which special member functions exist" PR (coming soon, almost finished) will add most of the infrastructure to determine whether a type has a trivial destructor. It won't be perfect, but it should be conservative (if it decides a type has a trivial destructor, then it definitely does, but some types with trivial destructors might not get flagged as such).

**Comment by adetaylor** [comment]
This is a serious bug. I don't understand how this is happening, as cxx should generate static assertions that make it impossible. Something is going wrong in the pipeline from autocxx->cxx->generated C++, and I'll look at this with high priority.

**Comment by bsilver8192** [comment]
Even if one of these types is never passed to another function, it will still call C++ destructors of member variables twice @adetaylor (once by the Rust member's `drop`, once by the enclosing class's destructor via the enclosing Rust object's `drop`). Do you want to reopen this or create a new issue for that?

**Comment by adetaylor** [comment]
That may be a separate issue, I will reopen and think about it.

**Comment by adetaylor** [comment]
Thanks a lot for the test case in #860, this makes sense now and I will aim to fix it in the next few days by emitting an extra `static_assert` to cover the cases where cxx doesn't.

**Comment by adetaylor** [comment]
Fixed by #861.
