### ISSUE TITLE
subclass generate issue

### ISSUE THREAD

**Issue by smileheart1990** [google/autocxx#863]
thanks for the crate, i study the example about subclass -> [https://github.com/google/autocxx/tree/main/examples/subclass](url) , but i dont want to use the auto_allowlist(true) in the build.rs for some reason, so i remove auto_allowlist(true) and add generate!("MessageDisplayer") in include_cpp,   its a pity the complier always said "cannot find type `UwuDisplayerCpp` in module `ffi`", it seems the subclass can only be  generated in auto_allowlist mode, can anyone help check this? much appreciate your help. and i have attached my version in the attachment.

- Version:0.1.16
- Platform:linux and macos
[subclass.zip](https://github.com/google/autocxx/files/8168256/subclass.zip)

**Comment by adetaylor** [comment]
I added a code example in #863 which should (in 10 minutes) appear at this page: https://google.github.io/autocxx/rust_calls.html

**Comment by smileheart1990** [comment]
> I added a code example in #863 which should (in 10 minutes) appear at this page: https://google.github.io/autocxx/rust_calls.html

thanks for your reply, adetaylo, it solved my problem
