### ISSUE TITLE
Figure out how to differentiate between pointer and reference member variables

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#865]
## Expected Behavior
Pointers allow an implicit default constructor on the containing type without an initializer, references don't.

## Actual Behavior
By the time the types make it through bindgen, all the members are pointers. It looks like there's a `#[cpp_semantics(reference)]` annotation which distinguishes them, but I'm not sure how to plumb that through.

## Steps to Reproduce the Problem

#843 is adding test cases with some commented-out parts that should pass once this is fixed.

**Comment by adetaylor** [comment]
Probably a duplicate of #761.
