### ISSUE TITLE
Implicit constructors for nested types were broken and are now disabled

### ISSUE THREAD

**Issue by adetaylor** [google/autocxx#884]
Tried to add this doctest, it doesn't work:

```rust

```rust,ignore,autocxx,hidecpp
autocxx_integration_tests::doctest(
"",
"
struct Turkey {
    struct Duck {
        struct Hen {
            int wings;
        };
    };
};
",
{
use autocxx::prelude::*;

include_cpp! {
    #include "input.h"
    safety!(unsafe_ffi)
    generate_pod!("Turkey_Duck_Hen")
}

fn main() {
    let turducken = ffi::Turkey_Duck_Hen::make_unique();
}
}
)
```

Says

```
1 | ..."] pub struct Turkey_Duck_Hen ; # [doc = "autocxx bindings couldn't be generated: This item name is used in multiple namespaces. At present, autocxx and cxx allow only one type of a given name. This limitation will be fixed in future."] pub struct Turkey_Duck_Hen ...```

**Comment by adetaylor** [comment]
This actually turns out to be a problem where we're creating a constructor called `Turkey_Duck_Hen` and is therefore probably a duplicate of #877.

**Comment by adetaylor** [comment]
The problem here is that the whole machinery for creating implicit constructors works with `QualifiedName` not `ApiName` and therefore does not track the C++ name separately. That's a problem for inner types, because that C++ name is used in constructing the `ideal_rust_name` for a function, which in turn is used as evidence that the function we're making is a constructor.

**Comment by adetaylor** [comment]
#884 disables generation of any implicit constructors for nested types.

We should fix this, but we should wait for #843 to land first, to avoid horrendous merge conflicts.

**Comment by bsilver8192** [comment]
I'm fixing this now. Proposing to do it separately from #843, but I'm partway there already.

**Comment by bsilver8192** [comment]
Ok, I've got a fix for this. Going to hold off making a PR because github's support for nested PRs is full of foot-guns.
