### ISSUE TITLE
Bindgen replacements for nested types don't work

### ISSUE THREAD

**Issue by bsilver8192** [google/autocxx#893]
## Expected Behavior
Using `<div rustbindgen replaces="A"></div>` for nested types should work.

## Actual Behavior
The autocxx-generated C++ uses incorrectly-qualified names for the replacement type.

## Steps to Reproduce the Problem

PR with a partially-commented-out test incoming.

**Comment by adetaylor** [comment]
Interesting! Can you talk more about your use case?

**Comment by bsilver8192** [comment]
I ran into this trying to work around #787.

Ran into further problems though, didn't finish understanding why that produces a different error yet. Maybe because it's a typedef or maybe because the final type is a template with specializations? It looks like bindgen is getting confused somewhere, vs for simpler cases (like the tests added in #895 ) I think it's just autocxx using the wrong name.

Specifically, I've got a clock structured similarly to the standard library ones:
```c++
class monotonic_clock {
 public:
  typedef ::std::chrono::nanoseconds::rep rep;
  typedef ::std::chrono::nanoseconds::period period;
  typedef ::std::chrono::nanoseconds duration;
  typedef ::std::chrono::time_point<monotonic_clock> time_point;
};
```
`monotonic_clock::time_point` gets used pretty extensively, so it'd be nice to just replace that with `struct rust_time_point { int64_t time_since_epoch; };` instead of having to wrangle each API being wrapped separately.

**Comment by adetaylor** [comment]
I see.

I think I'm not yet ready to declare that `<div rustbindgen replaces="A"></div>` is supported functionality for `autocxx`. Some folks think that autocxx's use of bindgen is really a hack. I prefer to think of it as "standing on the shoulders of giants"! - but I'd like to keep our options open for using libclang directly (or other tooling) for the parser in future. For that reason, I am not sure I want to support exposing bindgen-specific functionality to the user... or at least I want to think it through first.

Regarding #787: have you considered digging into that (bindgen) issue directly? Sometimes there are easy fixes there. Hopefully it's not something as horrid as https://github.com/rust-lang/rust-bindgen/issues/1924, on which I've been kind of stuck for over a year.

**Comment by bsilver8192** [comment]
Ah, that's what you're asking about: use cases for replacement types in general, not just nested ones. I'm also using it to work around #266. It'd be nice to fix that one too I guess.

In general, I'm finding the replacement feature handy for piecing something together that links, so I can find more problems faster. The problem with large C++ codebases is lots of things depend on each other, so it's hard to test Rust interop with the higher-level APIs by commenting out / etc the lower-level APIs that give autocxx problems, because then the C++ code doesn't compile+link.

**Comment by adetaylor** [comment]
Right ho.

I'm glad this technique is working for you, and it hadn't occurred to me to use this as a way to make progress through a big codebase. I'd been relying just on `block!` and desperately attempting to fix the underlying bugs each time I encountered one (or figure out a way to ignore such APIs). I will use this replacement technique in future.

.... But nevertheless, I'm not willing to declare this supported functionality which will be maintained, so at the moment I'm afraid I'm not going to accept #895.

If you find ways in which `block!` is deficient then let me know.

**Comment by bsilver8192** [comment]
Ok then, makes sense.
