### ISSUE TITLE
Encountered type not yet known by autocxx: [:: std :: os :: raw :: c_char ; 11usize]

### ISSUE THREAD

**Issue by smileheart1990** [google/autocxx#897]
thanks for this crate, i am faced with a problem, i want to call a C++ function in rust, the c++ code detail is like bellow,

typedef char TThostFtdcBrokerIDType[11];
//struct
struct CThostFtdcFensUserInfoField
{
TThostFtdcBrokerIDType BrokerID;
TThostFtdcUserIDType UserID;
TThostFtdcLoginModeType LoginMode;
};

// function
virtual void RegisterFensUserInfo(CThostFtdcFensUserInfoField * pFensUserInfo) = 0;

i generate the rust code follow the official steps, but it said, 

 ///autocxx bindings couldn't be generated: Encountered type not yet known by autocxx: [:: std :: os :: raw :: c_char ; 11usize]

it seems the char[11] is not supported in autocxx,  can any one help advise this? thanks in advance

- Version: linux and macos
- Platform:

**Comment by adetaylor** [comment]
That's right, they're not yet supported - #266. Happy to accept pull requests.

**Comment by smileheart1990** [comment]
thanks for your reply
