### ISSUE TITLE
POD struct member is missing, as well as documentation

### ISSUE THREAD

**Issue by TheButlah** [google/autocxx#966]
## Expected Behavior

calling `generate_pod!("MyStruct")` should generate a shared type with full ability to access the fields of the struct

### Inputs
Here is the C++ struct:
![image](https://user-images.githubusercontent.com/6969415/160357846-5ac77fb1-096f-4ad1-bad4-90b50cd0b20b.png)

Here is the generate_pod!() invocation:
![image](https://user-images.githubusercontent.com/6969415/160358634-8471f180-7d58-4db1-bf4f-0fe505bc9598.png)

### Outputs

I get this from bindgen, buried in the build directory, and not accessible to my code:
![image](https://user-images.githubusercontent.com/6969415/160357750-3def0d26-2caa-42d5-ae9c-980c263958eb.png)

as well as a typedef that is actually exposed to the user code: 
![image](https://user-images.githubusercontent.com/6969415/160357952-faba84cb-70c9-4618-a1b3-ecd8419d1d03.png)

In addition, the documentation for the POD type is missing, only the typedef shows up in the docs.

## Specifications

- Version: 0.17.2
- Platform: Windows 10

**Comment by TheButlah** [comment]
Actually, I think this is two things: 

1. my build.rs did not recompile so the generated output was out of date (it thought I hadn't used `generate_pod`
2. If I had generated it, I would have seen that arrays are not supported in autocxx right now (#266)

I am therefore closing this issue

**Comment by adetaylor** [comment]
Also, things have improved here since 17.2. do cargo update!
