### ISSUE TITLE
Cannot use cxx to define type that autocxx doesn't understand

### ISSUE THREAD

**Issue by TheButlah** [google/autocxx#967]
## Expected Behavior
According to [the manual](https://google.github.io/autocxx/workflow.html#how-to-work-around-cases-where-autocxx-cant-generate-bindings), you can write your own CXX bridge to define types that autocxx doesn't understand. I tried this with a type that I wanted to be a shared datatype between C++ and Rust, where the datatype was defined to begin with in C++. 

I expected that any signatures that used the offending type would use the type that I defined in the `cxx::bridge` module

## Actual Behavior

In reality, I don't see the module I wrote at all in the autogenerated code in the build directory, and the shared cxx type I expected to be there is missing when I ctrl-f. And autocxx still has generated the offending type as an opaque type with no methods on it, instead of using the (nonexistent) shared type.

## Steps to Reproduce the Problem

Here was the offending type that was defined in C++:
```c++
struct HmdMatrix34_t
{
	float m[3][4];  // this is the reason why autocxx messes up to begin with, it can't handle arrays rn
};
```

```rust

include_cpp! {
    #include "openvr.h"

    generate!("vr::IVROverlay")  // this has all of the functions that use `HmdMatrix34_t`
}

#[cxx::bridge(namespace = "vr")]
pub mod ffi2 {

    pub struct HmdMatrix34_t {
        pub m: [[f32; 4]; 3],  
    }

    unsafe extern "C++" {
        include!("openvr.h");
        type HmdMatrix34_t;
    }
}


pub use ffi::vr::*;
pub use ffi::{make_string, ToCppString};
pub use ffi2::HmdMatrix34_t;  // this doesn't seem to give me a compile err, yet it doesn't show up in the generated file
```

## Specifications

- Version: 0.17.2
- Platform: Windows 10

**Comment by TheButlah** [comment]
Related: #266

**Comment by adetaylor** [comment]
Thanks. Yep, the docs here weren't clear - I will clarify in #968. The only "supported" flow is to refer _from_ manual bindings _to_ automated bindings, not the other way round.

> In reality, I don't see the module I wrote at all in the autogenerated code in the build directory, 

That's normal. `cxx::bridge` doesn't generate any code to a file on disk - the macro is expanded when `rustc` compiles the code. You would need to use `cargo expand` or similar. See also the [hints here for how to see what's generated](https://google.github.io/autocxx/workflow.html#how-can-i-see-what-bindings-autocxx-has-generated).

So, at the moment, what you're trying to do is impossible.

I would be open to pull requests which do any of these:
* Add array support per #266
* Add methods to opaque types.
* Add the ability to refer _from_ automatically generated bindings _to_ manually generated bindings. I'm thinking this would be something like `extern_type!("vr::HmdMatrix34_t", ffi2::HmdMatrix34_t)`.

The intention would then be to allow `autocxx` to generate methods and functions which involve that type. That might be fairly easy. I'll keep this issue open to track that request.

NB I still don't think it would work _exactly_ like you want from your code snippet. By declaring the `pub struct` in the `cxx::bridge` outside the `extern "C++"` section, you're asking `cxx` to make a new set of C++ definitions for `HmdMatrix34_t`. They would likely conflict with the existing definition. But given `extern!` you could work around this by manually defining your `cxx::ExternType` definition.

**Comment by TheButlah** [comment]
> By declaring the pub struct in the cxx::bridge outside the extern "C++" section, you're asking cxx to make a new set of C++ definitions for HmdMatrix34_t

From the documentation [here](https://cxx.rs/shared.html#extern-enums), I believe the cxx binding will treat c++ as the source of truth and simply statically assert that the Rust definition matches. 

Does that change anything about what you said above?

I do think that supporting the ability to refer from autogenerated bindings to manually generated ones would be important.

> Add methods to opaque types.
What do you mean by this? I thought that we already can add methods to autocxx made types in the cxx bridge

**Comment by adetaylor** [comment]
> From the documentation [here](https://cxx.rs/shared.html#extern-enums), I believe the cxx binding will treat c++ as the source of truth and simply statically assert that the Rust definition matches. Does that change anything about what you said above?

I _think_ that's specifically true of enums. I may be wrong though.

I think if you want to refer to a pre-existing structs defined in pre-existing C++, you need to do [this instead](https://cxx.rs/extern-c++.html#integrating-with-bindgen-generated-or-handwritten-unsafe-bindings) (which is pretty much what autocxx is doing, but as noted, it doesn't work for arrays yet).

> Add methods to opaque types.

Ah I see what you mean now. The word "opaque" is overloaded. bindgen makes opaque types and autocxx does its best to ignore them and any functions/methods involving them. But, yes, you meant cxx opaque types.

**Comment by TheButlah** [comment]
Sorry, I'm a bit confused, as I am quite unfamiliar with the internal workings of cxx and autocxx.

Is there any workaround for my solution that doesn't involve an upstream feature contribution to autocxx? I don't think I have the knowledge to make actual changes to autocxx itself 😢

> you need to do [this instead](https://cxx.rs/extern-c++.html#integrating-with-bindgen-generated-or-handwritten-unsafe-bindings)

Is this a way that I can get autocxx to use bindgen generated types?

**Comment by adetaylor** [comment]
> Is this a way that I can get autocxx to use bindgen generated types? It looks like it would let me have cxx use bindgen, but I'm not sure if you're saying that it would also work for autocxx too

No, at the moment, this is not something you can do without an autocxx code change to add the `extern!` directive I propose above.

Watch this space - I'll probably get around to doing something here soon.

**Comment by TheButlah** [comment]
> Could I maybe transmute the autocxx opaque type into the bindgen created type? Or would this be unsound?

It was pretty clunky and a bit cursed, but since I'm wrapping the autocxx generated code in an ergonomic rust wrapper anyway, it was a viable option for me to do this:

```rust
/// Row-major 3x4 matrix
#[derive(Debug, PartialEq)]
#[repr(C)]
pub struct Matrix3x4(pub [[f32; 4]; 3]);
impl From<&Matrix3x4> for &sys::HmdMatrix34_t {
    fn from(other: &Matrix3x4) -> Self {
        let other = other as *const Matrix3x4;
        // safety: C++ POD types have same memory layout as order of fields
        //   so it is safe to cast it this way
        unsafe { &*other.cast() }
    }
}
impl From<&sys::HmdMatrix34_t> for &Matrix3x4 {
    fn from(other: &sys::HmdMatrix34_t) -> Self {
        let other = other as *const sys::HmdMatrix34_t;
        // safety: C++ POD types have same memory layout as order of fields
        //   so it is safe to cast it this way
        unsafe { &*other.cast() }
    }
}
impl From<&mut Matrix3x4> for &mut sys::HmdMatrix34_t {
    fn from(other: &mut Matrix3x4) -> Self {
        let other = other as *mut Matrix3x4;
        // safety: C++ POD types have same memory layout as order of fields
        //   so it is safe to cast it this way
        unsafe { &mut *other.cast() }
    }
}
impl From<&mut sys::HmdMatrix34_t> for &mut Matrix3x4 {
    fn from(other: &mut sys::HmdMatrix34_t) -> Self {
        let other = other as *mut sys::HmdMatrix34_t;
        // safety: C++ POD types have same memory layout as order of fields
        //   so it is safe to cast it this way
        unsafe { &mut *other.cast() }
    }
}
impl From<sys::HmdMatrix34_t> for Matrix3x4 {
    fn from(other: sys::HmdMatrix34_t) -> Self {
        // Get shrekt, autocxx 😎
        unsafe { std::mem::transmute(other) }
    }
}
impl From<Matrix3x4> for sys::HmdMatrix34_t {
    fn from(other: Matrix3x4) -> Self {
        unsafe { std::mem::transmute(other) }
    }
}
```

**Comment by adetaylor** [comment]
Status update:
* I haven't made any progress on `extern!`
* There is now very limited support for array fields within structs, thanks to @yshui in #969. I have no idea whether it will work for your use-case. I plan to add a raft more tests here at some stage to determine its limitations. This is not yet released, but it is merged to autocxx main.
